/* Content of the downloadable CV PDFs (public/cv/CV_Nikita_Petrich_{DE,EN}.pdf).
 *
 * The CV is a denser, print-only view of the same career as the website: it
 * carries more bullets per project than a project page does, and it is written
 * in the CV's own register. It therefore keeps its own copy of the wording
 * rather than being generated from lib/content/* — but the two must state the
 * same facts. When a date, a number or a claim changes, change it here *and*
 * in lib/content/projects.ts.
 *
 * Rendered by scripts/cv/build.mjs. Both languages are laid out by the same
 * template, so an entry that exists in one language must exist in the other. */

/** Rendered in the running header of every page. */
export const asOf = { de: "Stand: August 2026", en: "As of: August 2026" };

const contact = {
  phone: "+49 15679088678",
  mail: "n.petrich@sequenz.io",
  web: "sequenz.io",
  linkedin: "linkedin.com/in/nikita-petrich",
};

/* Marks a run of text as bold inside a paragraph or bullet: the template
   splits on **…** the way Markdown does, so the source stays readable. */
const de = {
  lang: "de",
  asOf: asOf.de,
  contact,
  headerName: "Nikita Petrich · Freiberuflicher Senior Full-Stack & AI Engineer",
  headerPlace: "München, Deutschland",
  pageLabel: "Seite",

  profile: {
    quote: "„Was zweimal manuell passiert, wird automatisiert“",
    name: "Nikita Petrich",
    role: "Freiberuflicher Senior Full-Stack & AI Engineer",
    photo: "profile.jpg",
    lines: [
      [
        { label: "Tel:", value: contact.phone, href: `tel:${contact.phone.replace(/\s/g, "")}` },
        { label: "Mail:", value: contact.mail, href: `mailto:${contact.mail}` },
        { label: "Web:", value: contact.web, href: `https://${contact.web}` },
      ],
      [
        {
          label: "Ort:",
          value:
            "Remote (bevorzugt) · München hybrid: 1–2 Tage/Woche · Fernreisen: 1–2 Tage/Monat (bei Bedarf)",
        },
      ],
      [
        { label: "Onboarding:", value: "Anreise vor Ort (bei Bedarf)" },
      ],
      [
        { label: "Verfügbar:", value: "ab sofort · Vollzeit (volle Kapazität)" },
        { label: "Stundensatz:", value: "auf Anfrage" },
      ],
      [
        { label: "Qualifikation:", value: "IHK-zertifizierter Fachinformatiker (Köln)" },
      ],
      [{ label: "Erfahrung:", value: "7+ Jahre" }],
    ],
    tagGroups: [
      {
        title: "Schwerpunkt",
        tags: [
          "LLM-Integration",
          "RAG",
          "DSGVO-konforme KI-Architektur",
          "KI-gestützte Automatisierung",
          "Agentic Coding / AI-Engineering",
          "TypeScript",
          "Python",
          "Backend (NestJS · Node.js · FastAPI)",
          "Frontend (Next.js · React · Angular)",
          "PostgreSQL",
          "Clean Architecture",
          "Microservices",
          "CI/CD",
          "Docker",
        ],
      },
      {
        title: "Sprachen",
        tags: ["Deutsch · Native", "Englisch · B2 · US-/EU-Remote-Team-Erfahrung"],
      },
      {
        title: "Arbeitsweise",
        tags: [
          "ergebnisorientiert",
          "eigenverantwortlich & zuverlässig",
          "autonome, asynchrone Arbeitsweise",
          "klare Kommunikation (DE/EN)",
        ],
      },
      {
        title: "Profile",
        tags: [
          { text: "Website", href: "https://sequenz.io" },
          { text: "LinkedIn", href: "https://linkedin.com/in/nikita-petrich" },
          { text: "GitHub", href: "https://github.com/nikita-petrich" },
          { text: "freelancermap", href: "https://www.freelancermap.de/profil/nikita-petrich" },
          { text: "Malt", href: "https://www.malt.de/profile/nikitapetrich" },
          { text: "Zertifikate", href: "https://sequenz.io/de/certificates" },
        ],
      },
    ],
    intro: [
      "Ich bin freiberuflicher Senior Full-Stack & AI Engineer mit Schwerpunkt auf KI: **LLM-Integration, RAG und KI-gestützte Automatisierung** – von der Architektur bis zum stabilen Produktivbetrieb.",
      "Mein Leitsatz: **Was zweimal manuell passiert, wird automatisiert.** Das gilt für die Prozesse meiner Kunden genauso wie für meine eigene Arbeit. In der Logistik spart ein von mir gebautes Tourverwaltungssystem **bis zu 1.000 Stunden pro Jahr** durch automatisierte Dokumentenprozesse, im Handel **bis zu 40 Stunden Verwaltungsarbeit pro Monat**, im Notariat sinken die telefonischen Rückfragen der Mandanten um **bis zu 70 %**.",
      "Dieselbe Konsequenz wende ich auf die Entwicklung selbst an: Ich arbeite durchgängig mit **Agentic-Coding- und AI-Engineering-Workflows** (Claude Code, Cursor, Code Rabbit, MCP) – spezifikationsgetrieben, mit KI-gestützter Testgenerierung und agentischen Review-Prozessen. Das ist keine Spielerei, sondern der Grund für außergewöhnliches Tempo bei gleichbleibender Qualität: eine vollständige Cross-Platform-App vom ersten Commit bis zur Übergabe **in rund zwei Monaten**, als alleiniger Entwickler.",
      "Wie ich arbeite: **eigenverantwortlich, remote und asynchron**. Ich brauche keine tägliche Steuerung, sondern ein klares Ziel – den Weg dorthin schneide ich selbst zu und melde mich, bevor etwas ins Rutschen kommt. Entscheidungen dokumentiere ich, Code kommt getestet und review-fähig, und ich sage früh, wenn eine Anforderung technisch teurer wird als gedacht. Kommunikation auf Deutsch und Englisch.",
      "Technisch: **TypeScript und Python**, Backend mit NestJS, Node.js und FastAPI, Frontend mit Next.js, React und Angular, dazu PostgreSQL, Docker, CI/CD und Cloud auf Azure oder GCP. Clean Architecture und Microservices sind Standard, **DSGVO-Konformität und Secure by Design** denke ich von Beginn an mit.",
      "Erprobt ist das im **20-köpfigen Engineering-Team** – zuletzt an einer KI-gestützten LegalTech-Plattform mit **über 3.000 Kunden** – ebenso wie als alleiniger Entwickler mit voller Produktverantwortung. In **über sieben Jahren** quer durch LegalTech, HealthTech, E-Commerce, EdTech und Logistik.",
    ],
    cta: {
      question: "Passt das zu Ihrem Vorhaben?",
      text: "Buchen Sie ein ",
      link: "kostenloses Erstgespräch",
      href: "https://calendar.notion.so/meet/petrichnikita/erstgespraech-30-min",
    },
  },

  skills: {
    title: "Skills & Fähigkeiten",
    subtitleA: "Vollständige Übersicht meiner technischen Kompetenzen",
    subtitleB: "Fortsetzung — Methodik, Compliance, Tooling & Domänen",
    categories: [
      {
        num: "01",
        name: "KI, LLM & AI Engineering",
        items: ["LLM-Integration", "RAG (Retrieval Augmented Generation)", "Prompt Engineering", "Embeddings", "Vektordatenbanken", "pgvector", "Semantische Suche", "Dokumentenanalyse", "OCR", "LangChain", "OpenAI API", "Azure OpenAI", "Anthropic Claude API", "Hugging Face", "Ollama", "KI-Agenten", "Agentic Software Engineering", "KI-gestützte Automatisierung", "AI Engineering", "Künstliche Intelligenz", "DSGVO-konforme KI-Architektur"],
      },
      {
        num: "02",
        name: "Agentic Coding",
        items: ["Claude Code", "Cursor AI", "GitHub Copilot", "Code Rabbit", "ChatGPT", "Lovable", "v0", "Claude Code Hooks", "Slash Commands", "Agent Skills", "Subagenten", "Multi-Agent-Workflows", "Model Context Protocol (MCP)", "Agentic Coding", "Context Engineering", "Spec-Driven Development", "Agentische Pull-Request-Workflows", "KI-gestützte Testgenerierung"],
      },
      {
        num: "03",
        name: "Programmiersprachen",
        items: ["TypeScript", "JavaScript", "Python", "C#", "SQL", "Bash", "HTML", "CSS", "SCSS", "XML", "UML"],
      },
      {
        num: "04",
        name: "Backend & Frameworks",
        items: ["Node.js", "NestJS", "Express.js", "Fastify", "FastAPI", "Flask", "ASP.NET Core", ".NET Core", "GraphQL", "REST API", "OpenAPI", "Swagger", "WebSockets", "Webhooks", "Message Queues", "BullMQ", "RabbitMQ", "Backend-Entwicklung", "Objektorientierte Programmierung (OOP)"],
      },
      {
        num: "05",
        name: "Frontend",
        items: ["React", "Next.js", "Angular", "React Native", "Ionic", "Capacitor", "Cross-Platform-Entwicklung", "iOS", "Android", "Redux", "NgRx", "RxJS", "TanStack Query", "React Hook Form", "React Router", "Axios", "Zod", "Tailwind CSS", "shadcn/ui", "Material UI (MUI)", "Fluent UI", "Single Page Application (SPA)", "Progressive Web App (PWA)", "Server-Side Rendering (SSR)", "Internationalisierung (i18n)", "Frontend-Entwicklung", "Web-Entwicklung"],
      },
      {
        num: "06",
        name: "Design & UX",
        items: ["Figma", "Wireframing", "Prototyping", "Design System", "Design Tokens", "Komponentenbibliotheken", "Storybook", "UI/UX Design", "UI-Implementierung", "Responsive Design", "Mobile First", "Barrierefreiheit (WCAG)", "Usability", "Nutzerführung", "Onboarding-Flows", "Informationsarchitektur", "UX Writing", "Microcopy", "Design Reviews"],
      },
      {
        num: "07",
        name: "Datenbanken & Daten",
        items: ["PostgreSQL", "MySQL", "MariaDB", "Microsoft SQL Server (MSSQL)", "MongoDB", "Mongoose", "NoSQL", "SQLite", "Redis", "Cloud Firestore", "Prisma", "MikroORM", "TypeORM", "Drizzle ORM", "Entity Framework Core", "Datenmodellierung", "Datenarchitektur", "DTOs", "Daten-Synchronisation", "ETL", "CSV-Verarbeitung", "Caching", "Idempotenz"],
      },
      {
        num: "08",
        name: "DevOps, Cloud & Infrastruktur",
        items: ["Docker", "Docker Compose", "CI/CD", "Continuous Integration", "GitHub Actions", "GitLab CI", "Azure Pipelines", "Jenkins", "Nginx", "Sentry", "Monitoring", "Observability", "Linux", "Ubuntu", "Self-Hosting", "Microsoft Azure", "Azure Functions", "Azure App Service", "Azure Blob Storage", "Azure SQL", "Google Cloud Platform (GCP)", "Amazon Web Services (AWS)", "Hetzner", "IONOS", "Digital Ocean", "Vercel", "Supabase", "Firebase", "Cloud Functions", "Cloud Storage", "Firebase Cloud Messaging (FCM)", "Firebase Hosting", "DevOps", "DevSecOps"],
      },
      {
        num: "09",
        name: "Auth & Security",
        items: ["JWT", "OAuth 2.0", "Single Sign-On (SSO)", "better-auth", "Firebase Authentication (Auth)", "Firebase Security Rules", "Authentifizierung", "Role-Based Access Control (RBAC)", "Row Level Security", "SSL/TLS", "Ende-zu-Ende-Verschlüsselung", "O365 Identity", "Microsoft Entra ID (ehem. Azure Active Directory)", "Secure by Design", "IT-Sicherheit"],
      },
      {
        num: "10",
        name: "Architektur & Prinzipien",
        items: ["Software-Architektur", "Clean Architecture", "Clean Code", "SOLID", "Design Patterns", "Domain-Driven Design", "Separation of Concerns", "Dependency Injection", "Microservices", "Event-Driven Architecture", "Monorepo", "Nx", "Turborepo", "Skalierbare Architektur", "Systemintegration", "Plattform-Migration", "Middleware", "API-First", "Resilience Patterns", "Typsicherheit", "MVP-Entwicklung"],
      },
      {
        num: "11",
        name: "Methodik & Zusammenarbeit",
        items: ["Agile Methoden", "Scrum", "Kanban", "Scrumban", "Code Reviews", "Test-Driven Development (TDD)", "Softwareentwicklung", "Projektmanagement", "IT-Beratung", "Requirements Engineering", "Remote Work", "Public Speaking"],
      },
      {
        num: "12",
        name: "Business & Strategie",
        items: ["IT-Strategie", "Digitalstrategie", "Digitale Transformation", "Prozessdigitalisierung", "Produktverantwortung", "Entrepreneurship"],
      },
      {
        num: "13",
        name: "Datenschutz & Compliance",
        items: ["DSGVO", "Privacy by Design", "Datenminimierung", "Auftragsverarbeitungsvertrag (AVV)", "EU AI Act", "AI Governance", "GoBD", "Revisionssicherheit", "EU-Hosting", "Digitale Souveränität", "Barrierefreiheitsstärkungsgesetz (BFSG)", "European Accessibility Act (EAA)"],
      },
      {
        num: "14",
        name: "Testing & QA",
        items: ["Jest", "Vitest", "Cypress", "Playwright", "React Testing Library", "Unit Testing", "Integrationstests", "End-to-End-Tests", "Postman", "API-Testing", "Testautomatisierung"],
      },
      {
        num: "15",
        name: "Tooling",
        items: ["Git", "GitHub", "GitLab", "Husky", "Visual Studio Code", "Visual Studio", "Jira", "Linear", "Azure DevOps", "Bluedot", "HubSpot", "Cal.com", "Slack", "Google Workspace (Meet, APIs)", "Amplitude", "Product Analytics"],
      },
      {
        num: "16",
        name: "Domänen & Branchen",
        items: ["LegalTech", "GovTech", "Kanzleisoftware", "Notariat", "Mandantenportal", "Dokumentenmanagement", "HealthTech", "Medizintechnik", "Instandhaltungsmanagement", "ERP", "Warenwirtschaft", "Lagerverwaltung", "Rechnungsstellung", "Auftragsverwaltung", "CRM", "Buchhaltung", "Stammdatenverwaltung", "Multi-Tenancy", "Stripe", "SEPA", "Zahlungsabwicklung", "Logistik", "Tourenplanung", "PDF-Generierung", "DOCX-Generierung", "Digitale Archivführung", "EdTech", "E-Learning", "Learning Management System (LMS)", "IoT", "Device Pairing", "Consumer Electronics", "Social Media", "SaaS", "Plattformentwicklung"],
      },
      {
        num: "17",
        name: "Rollen & Profil",
        items: ["Senior Full-Stack Engineer", "AI Engineer", "Software Engineer", "Freelance Developer", "Interim CTO", "Technischer Berater", "Fachinformatiker Anwendungsentwicklung", "Deutsch (Muttersprache)", "Englisch B2", "München", "DACH"],
      },
    ],
  },

  overview: {
    title: "Projektübersicht",
    subtitle: "Alle Projekte im Überblick — mit Direktsprung zur jeweiligen Detailseite",
  },

  labels: {
    role: "Rolle:",
    client: "Kunde:",
    team: "Team:",
    location: "Standort:",
    language: "Projektsprache:",
    website: "Website:",
    method: "Methodik:",
    visibility: "Sichtbarkeit:",
    responsibilities: "Aufgaben",
    results: "Ergebnis",
    technologies: "Technologien",
    recommendation: "Empfehlung",
  },

  projects: [
    {
      num: "01",
      cat: "LegalTech / GovTech",
      period: "04/2025 – heute · 15 Monate",
      dates: "04/2025 – heute",
      duration: "~15 Monate",
      name: "BESCHEIDKLAR",
      subtitle: "KI-gestützte LegalTech-SaaS-Plattform",
      role: "Gründer & CTO",
      client: "Eigenprodukt",
      clientHref: "https://bescheidklar.de",
      overviewRole: "Gründer & CTO",
      cover: "bescheidklar.jpg",
      meta: [
        { label: "Team:", value: "Solo (alleiniger Entwickler) · Eigenprodukt (nebenberuflich)" },
        { label: "Standort:", value: "Niedersachsen, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Website:", value: "bescheidklar.de", href: "https://bescheidklar.de" },
        { label: "Methodik:", value: "Eigenverantwortlich · direkte Produktverantwortung" },
      ],
      responsibilities: [
        "Konzeption und Aufbau einer zweiseitigen Legal-Tech-SaaS-Plattform mit modularer, service-orientierter Architektur – Verbindung KI-gestützter Dokumentenanalyse (**Azure OpenAI**) mit einem regionalen Lizenzmodell für Anwaltskanzleien.",
        "Konzeption und Umsetzung einer mehrstufigen **KI-Vorprüfungs-Pipeline** für Bescheide und Kündigungen (in Umsetzung): Extraktion → Fristprüfung → Plausibilitäts- und Erfolgseinschätzung mit strukturierter Aufbereitung des Falls.",
        "Automatisierte, DSGVO-konforme Übergabe qualifizierter Leads (inkl. hochgeladener bzw. fotografierter Dokumente, Berechnungen und KI-Ergebnissen) direkt in das System der passenden Spezialisten (Rechtsanwälte, Law Clinics) – inklusive Kontaktdaten, sodass ein sofort bearbeitbarer Mandats-Lead entsteht.",
        "Umsetzung eines KI-gestützten Ratgeber-Bereichs mit **RAG**-basierter Inhaltsaufbereitung – Artikel und Handlungsempfehlungen für Betroffene (z. B. nach Kündigung oder Ablehnungsbescheid).",
        "Abdeckung mehrerer Rechtsbereiche (Rechts-, Sozial- und Arbeitswesen) über eine erweiterbare, mehrsprachige und barrierearme Weboberfläche.",
        "Gesamtverantwortung für Architektur, Tech-Stack, Hosting auf EU-Infrastruktur und ein Secure-by-Design-Compliance-Konzept (**EU AI Act**, **DSGVO**, **RDG**).",
        "Aufbau typsicherer End-to-End-Datenflüsse (**TypeScript**, **DTOs**, **Zod**) mit automatisierter **CI/CD**-Auslieferung (**GitHub Actions**, **Docker**), Monitoring/Fehler-Tracking (**Sentry**) und Test-Abdeckung (**Vitest**, **Playwright**).",
      ],
      results: [
        "MVP in Eigenregie umgesetzt – Architektur, Plattform und Betrieb auf EU-Infrastruktur aus einer Hand.",
        "Compliance im Produktdesign verankert statt nachgerüstet: EU AI Act, DSGVO und die Grenzen des RDG von Beginn an eingeplant.",
        "Adressierbarer Markt: **167.547** zugelassene Rechtsanwältinnen und Rechtsanwälte in Deutschland (BRAK, 01.01.2026); skalierbares Modell bei minimalen Fixkosten.",
        "Ziel: bis zu **10.000** automatisierte Vorprüfungen pro Monat durch KI-gestützte Ersteinschätzung.",
        "Ziel: bis zu **80 %** weniger manuelle Fallannahme durch KI-Intake und automatisiertes Anwalts-Routing.",
        "Ziel: planbarer Zustrom vorqualifizierter Mandate für angebundene Kanzleien statt aufwändiger manueller Ersteinschätzung.",
      ],
      tech: ["TypeScript", "Python", "Next.js", "React", "FastAPI", "LLM-Integration", "OpenAI API", "Azure OpenAI", "RAG (Retrieval Augmented Generation)", "Prompt Engineering", "Embeddings", "pgvector", "OCR", "Dokumentenanalyse", "LangChain", "PostgreSQL", "Redis", "Tailwind CSS", "shadcn/ui", "Stripe", "JWT", "OAuth 2.0", "Docker", "GitHub Actions", "CI/CD", "Hetzner", "Linux", "Ubuntu", "Slack", "Husky", "Microservices", "Clean Architecture", "SaaS", "EU AI Act", "DSGVO", "Privacy by Design", "Produktverantwortung"],
    },
    {
      num: "02",
      cat: "LegalTech / Immigration",
      period: "12/2025 – 04/2026 · 5 Monate",
      dates: "12/2025 – 04/2026",
      duration: "~5 Monate",
      name: "Manifest OS",
      subtitle: "KI-gestützte Einwanderungsplattform",
      role: "Full-Stack Engineer (KI-Feature-Integration)",
      client: "Manifest Law",
      clientHref: "https://manifestlaw.com",
      overviewRole: "Full-Stack (KI-Features)",
      recommendation: true,
      cover: "manifest-os.jpg",
      meta: [
        {
          label: "Team:",
          value:
            "~20 Engineers in 4 Teams (Platform, AI, Fullstack) · crossfunktionale Zusammenarbeit mit Produkt, Design und Tech-Leads",
        },
        { label: "Standort:", value: "New York, USA · Remote" },
        { label: "Projektsprache:", value: "Englisch" },
        { label: "Website:", value: "manifestlaw.com", href: "https://manifestlaw.com" },
        { label: "Methodik:", value: "Scrum · autonome Arbeitsweise" },
      ],
      responsibilities: [
        "Eigenständige Implementierung produktiver KI-Features: ereignisgesteuerte Anreicherung anwaltlicher Erstgespräch-Leads – Meeting-Aufzeichnungen werden per **Bluedot** transkribiert und über einen Webhook, eine **BullMQ**-Queue und die **OpenAI**-Integration resilient (Retry, Idempotenz) weiterverarbeitet; strukturierte Ergebnisse fließen automatisiert in die Kernsysteme zurück.",
        "KI-gestützte Evidence-Verarbeitung: hochgeladene Falldokumente (z. B. Ausweis-Scans, Geburtsurkunden, Nachweise) werden automatisiert analysiert, klassifiziert und einheitlich benannt.",
        "Mitwirkung an der Konsolidierung von vier getrennten Portalen (B2B, B2C, Lawyer, Ops) und einer API in ein einheitliches „B2X“-Portal – im Team aus vier Engineers, mit verantwortlicher Fullstack-Migration der B2B- und Ops-Bereiche inkl. Zusammenführung von Datenmodell und UI.",
        "Einführung eines anwendungsweiten Event-Trackings (**Amplitude**) zur Analyse des Nutzerverhaltens – Identifikation von Schwachstellen und Reibungspunkten als Datengrundlage für Produkt- und Data-Analytics.",
        "Entwicklung robuster, ereignisgetriebener Backend-Services (**NestJS**, **BullMQ**) mit Retry-, Idempotenz- und Fehlerbehandlungs-Strategien für eine zuverlässige Hintergrundverarbeitung.",
        "Umsetzung im Monorepo mit klar abgegrenzten Feature-Modulen für eine zukünftig möglichst schnelle Aufteilung in Microservices, mit typsicheren Schnittstellen (**TypeScript**, **DTOs**) sowie automatisierten Tests (**Jest**, **Playwright**) im CI/CD-Prozess.",
        "Enge Zusammenarbeit in Code-Reviews und Einsatz KI-gestützter Werkzeuge (**Claude Code**, **Cursor AI**, **Code Rabbit**) zur Sicherung von Qualität und Entwicklungstempo.",
      ],
      results: [
        "Teil eines rund 20-köpfigen Engineering-Teams an einer etablierten Plattform (Unternehmensbewertung im Bereich von rund **60 Mio. USD**).",
        "KI-Features im Produktivbetrieb: Erstgespräch-Leads und Falldokumente werden ohne manuelle Nacharbeit angereichert, klassifiziert und benannt.",
        "Anwendungsweites Event-Tracking als gemeinsame Datengrundlage für Produkt- und Data-Analytics etabliert.",
        "Refactoring-Initiativen in den migrierten B2B- und Ops-Bereichen: bestehende Strukturen vereinfacht und auf bessere Wartbarkeit ausgerichtet.",
        "Plattform mit **über 3.000 Kunden**, **150+** Corporate-Programmen und über 100 Anwältinnen und Anwälten (Team-Ergebnis).",
        "Bis zu **15 %** höhere Genehmigungsraten gegenüber dem USCIS-Durchschnitt (Team-Ergebnis).",
      ],
      tech: ["TypeScript", "Python", "Next.js", "React", "NestJS", "Node.js", "Fastify", "Express.js", "REST API", "Webhooks", "DTOs", "BullMQ", "RabbitMQ", "LLM-Integration", "OpenAI API", "Anthropic Claude API", "Model Context Protocol (MCP)", "Bluedot", "HubSpot", "Cal.com", "Amplitude", "PostgreSQL", "Redis", "MikroORM", "TanStack Query", "better-auth", "JWT", "Docker", "Linux", "Ubuntu", "Google Cloud Platform (GCP)", "GitHub Actions", "CI/CD", "Claude Code", "Cursor AI", "Code Rabbit", "Linear", "Figma", "Slack", "Playwright", "Husky", "Microservices", "Event-Driven Architecture", "Idempotenz", "Clean Architecture"],
    },
    {
      num: "03",
      cat: "Social Media / Mobile App",
      period: "11/2025 – 12/2025 · 2 Monate",
      dates: "11/2025 – 12/2025",
      duration: "~2 Monate",
      name: "RateUp",
      subtitle: "Bewertungs-App für Web, iOS und Android",
      role: "Sole Developer · Full-Stack",
      client: "Krutzfeld Tech GmbH",
      clientHref: "https://krutzfeld.tech",
      overviewRole: "Sole Developer · Full-Stack",
      cover: "rate-up.jpg",
      meta: [
        { label: "Team:", value: "Solo (alleiniger Entwickler) · Kundenprojekt" },
        { label: "Standort:", value: "Zürich, Schweiz · Remote" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Website:", value: "krutzfeld.tech", href: "https://krutzfeld.tech" },
        { label: "Methodik:", value: "Eigenverantwortlich" },
      ],
      responsibilities: [
        "Konzeption und Umsetzung einer Bewertungs-App im Social-Media-Umfeld (Feed, Bewertungen, Profile) aus einer einzigen **Ionic-/Angular**-Codebasis – als installierbare **PWA** im Web sowie als native Builds für **iOS** und **Android** (**Capacitor**).",
        "Registrierung, Login und Onboarding inkl. Profilerstellung über **Firebase Authentication**, abgesichert durch **Firebase Security Rules**.",
        "Umsetzung des Social-Media-Feeds mit Filtern, eigenen Beiträgen und Media-Upload (**Cloud Firestore**, **Cloud Storage**).",
        "Serverseitige Logik in **Cloud Functions** sowie Auslieferung über **Firebase Hosting** und eine **CI/CD**-Pipeline (**GitHub Actions**) für alle drei Plattformen.",
        "Aufbau einer wartbaren, übergabefähigen Codebasis: klar geschichtete Struktur, wiederverwendbare Komponenten, typsichere Modelle, Unit-Tests und durchgängiger Clean-Code-Stil (**SOLID**).",
      ],
      results: [
        "Fertiges Produkt an den Kunden übergeben – lauffähig als PWA im Web und als native App auf iOS und Android aus einer gemeinsamen Codebasis.",
        "Vollständig auf **Firebase** aufgesetzt: Authentifizierung, Datenhaltung, Media-Storage, Serverlogik und Auslieferung.",
        "Übergabefähige Codebasis: einheitliche Struktur, wiederverwendbare Komponenten, Unit-Tests und durchgängige Typsicherheit – das Kundenteam kann ohne Einarbeitungshürde weiterarbeiten.",
        "Von der ersten Zeile bis zur Übergabe **in rund zwei Monaten**.",
      ],
      tech: ["TypeScript", "Angular", "Ionic", "Capacitor", "RxJS", "Cross-Platform-Entwicklung", "iOS", "Android", "Progressive Web App (PWA)", "Responsive Design", "UI-Implementierung", "Nutzerführung", "Firebase", "Firebase Authentication (Auth)", "Firebase Security Rules", "Cloud Firestore", "Cloud Storage", "Cloud Functions", "Firebase Cloud Messaging (FCM)", "Firebase Hosting", "Authentifizierung", "Onboarding-Flows", "Social Media", "Typsicherheit", "Unit Testing", "Clean Code", "SOLID", "Separation of Concerns", "Clean Architecture", "Git", "GitHub", "GitHub Actions", "CI/CD", "Linux", "Trello"],
    },
    {
      num: "04",
      cat: "IoT / Consumer Electronics",
      period: "08/2025 – 09/2025 · 2 Monate",
      dates: "08/2025 – 09/2025",
      duration: "~2 Monate",
      name: "AITOI",
      subtitle: "Interaktives IoT-Spielzeug (MVP)",
      role: "Frontend Engineer",
      client: "AITOI",
      overviewRole: "Frontend Engineer",
      recommendation: true,
      cover: "aitoi.jpg",
      meta: [
        { label: "Team:", value: "Kleines interdisziplinäres Team inkl. Hardware-Entwicklung" },
        { label: "Standort:", value: "Frankfurt, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch & Englisch" },
        { label: "Sichtbarkeit:", value: "internes System (Code nicht öffentlich)" },
        { label: "Methodik:", value: "Eigenverantwortlich · englischsprachige Abstimmung mit Hardware-Team" },
      ],
      responsibilities: [
        "Konzeption und Umsetzung des IoT-WLAN-Onboardings eines vernetzten KI-Spielzeugs per QR-Code-Scan – inkl. geführtem Einrichtungs-Flow, Gerätekopplung und robuster Fehlerbehandlung.",
        "Implementierung der Erst-Einrichtung neuer Geräte sowie der nachträglichen Konfiguration von Einstellungen über eine plattformunabhängige **Progressive Web App** (PWA).",
        "PWA-Dashboard für Eltern: Spielsessions der Kinder nachverfolgen, filtern und auswerten.",
        "Anbindung von **Supabase** für Authentifizierung, Datenhaltung und Echtzeit-Synchronisation zwischen Gerät und App (inkl. **Row Level Security**).",
        "Aufbau einer performanten, plattformunabhängigen PWA-Architektur (**Next.js**) mit responsivem UI.",
        "Definition und Umsetzung typsicherer Datenmodelle und API-Schnittstellen (**TypeScript**, **DTOs**, **Zod**).",
        "Enge, englischsprachige Abstimmung mit dem Hardware-Team zur Definition der Geräte-App-Kommunikation und der Setup-Protokolle.",
        "Beratung und Navigation des Kunden von der ersten Idee bis zum umsetzbaren **MVP**-Konzept.",
      ],
      results: [
        "Voll funktionsfähiges **MVP**-Frontend in **~2–3 Wochen reiner Arbeitszeit** – eigenständig von Konzept über Kundenabstimmung bis zur Demo umgesetzt.",
        "Setup-App und Eltern-Dashboard als eine plattformunabhängig nutzbare PWA mit Echtzeit-Synchronisation zwischen IoT-Gerät und App.",
        "Skalierbare, dokumentierte Architektur als tragfähige technische Grundlage für den Produktlaunch.",
        "Vertrauensvolle, funktionsübergreifende Zusammenarbeit mit dem Hardware-Team über die gesamte Projektlaufzeit – trotz kurzer Taktung ohne Reibungsverluste an der Geräte-App-Schnittstelle.",
      ],
      tech: ["TypeScript", "Next.js", "React", "Progressive Web App (PWA)", "Responsive Design", "Design System", "React Hook Form", "DTOs", "Device Pairing", "Supabase", "Supabase Realtime", "Row Level Security", "PostgreSQL", "Tailwind CSS", "shadcn/ui", "JWT", "Authentifizierung", "Docker", "Linux", "Ubuntu", "CI/CD", "GitHub Actions", "Vitest", "Cursor AI", "Model Context Protocol (MCP)", "MVP-Entwicklung", "Clean Architecture"],
    },
    {
      num: "05",
      cat: "LegalTech / Notariat",
      period: "01/2025 – 05/2025 · 5 Monate",
      dates: "01/2025 – 05/2025",
      duration: "~5 Monate",
      name: "DiNo",
      subtitle: "Digitales Notariat",
      role: "Frontend Engineer",
      client: "LeXtorByte UG",
      clientHref: "https://digitales-notariat.de",
      overviewRole: "Frontend",
      recommendation: true,
      cover: "dino.jpg",
      meta: [
        { label: "Team:", value: "2–4 Personen" },
        { label: "Standort:", value: "Oranienburg, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Website:", value: "digitales-notariat.de", href: "https://digitales-notariat.de" },
        { label: "Methodik:", value: "Scrumban" },
      ],
      responsibilities: [
        "Implementierung von Frontend-Features zur Digitalisierung von Notarprozessen mit Fokus auf klare, nachvollziehbare Nutzerführung – u. a. Mandantenportal und Notarportal.",
        "Umsetzung digitaler Vorgangsverwaltung: strukturierte Datenerfassung, digitale Verfahrensakten und nahtlose interne Ablage zur Beschleunigung der Fallbearbeitung.",
        "Mitwirkung am Ausbau eines Mandantenportals zur Statusverfolgung, sicheren Dokumentenbereitstellung und datenschutzkonformen Kommunikation.",
        "Aufbau wiederverwendbarer Komponenten und einheitlicher Formular-Validierung (**React Hook Form**) zur Beschleunigung der Feature-Entwicklung im gesamten Team.",
        "Eigeninitiative in der Codebasis: bestehenden Code refactored und Altfehler behoben – ausgerichtet auf langfristig tragfähige Lösungen.",
        "Enge Abstimmung mit Design und Backend im **Scrumban**-Rhythmus, um neue Anforderungen zügig in nutzbare Oberflächen zu übersetzen.",
      ],
      results: [
        "Laut Anbieter bis zu **70 %** weniger telefonische Rückfragen der Mandanten.",
        "Rechnungen werden laut Anbieter bis zu **30 Tage** früher bezahlt.",
        "Spürbar reduzierter Verwaltungsaufwand und höhere Transparenz durch durchgängig digitale, nachvollziehbare Prozesse.",
        "Konsistentes, modernes UI über Mandanten- und Notarportal hinweg, das Vertrauen bei Mandanten und Effizienz im Notariat gleichermaßen stärkt.",
      ],
      tech: ["TypeScript", "React", "Python", "Flask", "REST API", "OpenAPI", "DTOs", "MariaDB", "MySQL", "Redux", "React Router", "React Hook Form", "Material UI (MUI)", "Single Page Application (SPA)", "Nutzerführung", "Mandantenportal", "Digitale Archivführung", "JWT", "OAuth 2.0", "Role-Based Access Control (RBAC)", "DSGVO", "Docker", "Nginx", "Linux", "Ubuntu", "GitLab", "Slack", "Clean Architecture"],
    },
    {
      num: "06",
      cat: "Handel & Kfz-Gewerbe (Warenwirtschaft)",
      period: "01/2024 – 12/2024 · 12 Monate · laufende Wartung (nebenberuflich)",
      dates: "01/2024 – 12/2024",
      duration: "~12 Monate",
      name: "AccountingOS",
      subtitle: "GoBD-konformes Buchhaltungs- & Lagersystem",
      role: "Sole Developer · Full-Stack & AI",
      client: "HD Autoservice",
      overviewRole: "Sole Developer",
      recommendation: true,
      cover: "accounting-os.jpg",
      meta: [
        { label: "Team:", value: "Solo (alleiniger Entwickler) · Kundenprojekt" },
        { label: "Standort:", value: "Salzgitter, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Sichtbarkeit:", value: "internes System (Code nicht öffentlich)" },
        { label: "Methodik:", value: "Eigenverantwortlich" },
      ],
      responsibilities: [
        "Konzeption und Entwicklung eines **GoBD**-konformen Buchhaltungs- und Lagermanagementsystems mit vielen Funktionen auf Basis einer sauber geschichteten Architektur (**Clean Architecture**).",
        "Entwurf und Implementierung eines resilienten Daten-Synchronisationsservices („Pipe Service“), der Lieferanten-Kataloge (Autoersatzteile) mit bis zu **20 Mio.** CSV-Zeilen über eine TLS-verschlüsselte Verbindung verarbeitet – mit Queue, Caching, Retry-Logik, Validierung, Deduplizierung und Datenbereinigung.",
        "Umsetzung des Buchhaltungsmoduls: Rechnungen, Korrekturrechnungen, interne Aufträge, PDF-Export, Kundenverwaltung, **Lagerverwaltung**, Bestellimport mit automatischer Auftragskonvertierung sowie **GoBD**-Festschreibung.",
        "Kopplung der **Lagerverwaltung** an das Rechnungsmanagement: automatische Bestandsabbuchung bei Rechnungspositionen und Benachrichtigung bei Unterschreiten des Mindestbestands.",
        "Rekursive Auflösung von Fremdschlüssel-Abhängigkeiten in den Eingabedialogen für eine konsistente Stammdatenpflege.",
        "Kunden- und **Stammdatenverwaltung** mit rollenbasierter Zugriffssteuerung (Admin, Mitarbeiter, Steuerberater) und Authentifizierung via **better-auth**.",
        "Technische Beratung des Kunden zu Lösungsansätzen, Architektur und Prozessoptimierung.",
        "Aufbau typsicherer **GraphQL**- und REST-Schnittstellen (**NestJS**) mit Validierung, Fehlerbehandlung und konsistenter Datenmodellierung (**MikroORM**, **DTOs**).",
        "Laufende Betreuung (nebenberuflich): Wartung, Security-Updates und Weiterentwicklung.",
      ],
      results: [
        "Spart laut Kunde bis zu **40 Stunden** Verwaltungsarbeit pro Monat (bis zu **480 Stunden/Jahr**) – bei kalkulatorisch 40 € Arbeitskosten je Stunde rund **19.200 €** im Jahr.",
        "Reduziert den Zeitaufwand bei Routineprozessen wie Rechnungsstellung und **Lagerverwaltung** um bis zu **50 %**.",
        "Durchgängig digitale, **GoBD**-konforme Abläufe mit direkter Kopplung von Lager und **Buchhaltung**.",
      ],
      tech: ["TypeScript", "Node.js", "NestJS", "Next.js", "React", "Fastify", "REST API", "GraphQL", "DTOs", "Typsicherheit", "Daten-Synchronisation", "CSV-Verarbeitung", "Message Queues", "Caching", "MariaDB", "PostgreSQL", "Redis", "MikroORM", "TanStack Query", "Tailwind CSS", "Warenwirtschaft", "Lagerverwaltung", "Buchhaltung", "ERP", "GoBD", "better-auth", "JWT", "Role-Based Access Control (RBAC)", "Docker", "Self-Hosting", "Linux", "Ubuntu", "CI/CD", "GitHub", "GitHub Actions", "Husky", "Claude Code", "Cursor AI", "Model Context Protocol (MCP)", "Microservices", "Clean Architecture"],
    },
    {
      num: "07",
      cat: "Logistik & Transport",
      period: "02/2021 – 05/2023 · 2 Jahre 4 Monate · laufende Wartung (nebenberuflich)",
      dates: "02/2021 – 05/2023",
      duration: "~2 Jahre 4 Monate",
      name: "Ladetrans",
      subtitle: "LKW-Tourverwaltung für eine humanitäre Hilfsorganisation",
      role: "Sole Developer · Full-Stack & AI",
      client: "CDH Stephanus",
      clientHref: "https://cdh-stephanus.org",
      overviewRole: "Sole Developer",
      cover: "lkw-tourverwaltung.jpg",
      meta: [
        { label: "Team:", value: "Solo (alleiniger Entwickler) · Kundenprojekt" },
        { label: "Standort:", value: "Bremen, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Website:", value: "cdh-stephanus.org", href: "https://cdh-stephanus.org" },
        { label: "Methodik:", value: "Eigenverantwortlich" },
      ],
      responsibilities: [
        "Ladelisten je Tour: zu versendende Ware, Empfängeradressen und Fahrer in einem Vorgang zusammengestellt.",
        "Jede Tour als durchgängiger Vorgang – anlegen, bearbeiten, abschließen und archivieren.",
        "Automatisierte Generierung der Tourunterlagen aus den erfassten Daten, u. a. für Grenzkontrollen.",
        "Revisionssichere Archivierung abgeschlossener Touren inkl. der am Tourende hochgeladenen Nachweise.",
        "Alleinverantwortung für Backend-Architektur (**NestJS**, **Clean Architecture**), rollenbasierte Zugriffssteuerung (**better-auth**) und das selbst gehostete Deployment (**Docker**, **Nginx**) inkl. laufender Wartung (nebenberuflich).",
      ],
      results: [
        "Spart durch automatisierte Dokumentenprozesse laut Kunde bis zu **1.000 Stunden** pro Mitarbeiter und Jahr – bei kalkulatorisch 40 € Arbeitskosten je Stunde rund **40.000 €** jährlich.",
        "Laut Kunde bis zu **30 %** höhere Logistikeffizienz durch die durchgängige Verwaltung der Versandtouren.",
        "Deutlich reduzierte Übertragungsfehler; jede Tour ist mit Unterlagen und Nachweisen revisionssicher archiviert.",
      ],
      tech: ["TypeScript", "Node.js", "NestJS", "Next.js", "React", "Fastify", "REST API", "GraphQL", "PostgreSQL", "Redis", "MikroORM", "React Router", "Tailwind CSS", "Single Page Application (SPA)", "Logistik", "Tourenplanung", "PDF-Generierung", "DOCX-Generierung", "Digitale Archivführung", "better-auth", "JWT", "Authentifizierung", "Role-Based Access Control (RBAC)", "Docker", "Self-Hosting", "Linux", "Ubuntu", "CI/CD", "GitHub Actions", "Husky", "Claude Code", "Cursor AI", "Model Context Protocol (MCP)", "Slack", "Nginx", "Microservices", "Clean Architecture"],
    },
    {
      num: "08",
      cat: "EdTech / E-Learning",
      period: "05/2020 – 02/2023 · 2 Jahre 10 Monate",
      dates: "05/2020 – 02/2023",
      duration: "~2 Jahre 10 Monate",
      name: "XU Navigator",
      subtitle: "Enterprise-Lernplattform",
      role: "Full-Stack Engineer",
      client: "XU Group",
      clientHref: "https://xu.de",
      overviewRole: "Full-Stack",
      recommendation: true,
      cover: "xu-navigator.jpg",
      meta: [
        { label: "Team:", value: "5–10 Personen" },
        { label: "Standort:", value: "Bremen, Deutschland · Remote" },
        { label: "Projektsprache:", value: "Deutsch & Englisch" },
        { label: "Website:", value: "xu.de", href: "https://xu.de" },
        { label: "Methodik:", value: "Scrum" },
      ],
      responsibilities: [
        "Mitentwicklung des „XU Navigator“, einer skalierbaren Microservice-Lernplattform für Unternehmensmitarbeitende – u. a. für Kunden wie **Daimler**, **VW** und **ThyssenKrupp**.",
        "Entwicklung dynamisch, mandantenspezifisch befüllbarer Kursinhalte (Videos, Podcasts, Multiple-Choice-Fragen, Artikel) über klar abgegrenzte Services.",
        "Implementierung einer Lernfortschrittskontrolle inkl. automatischer Zertifikatsgenerierung sowie eines Experten- und Community-Forums.",
        "Full-Stack-Entwicklung über alle Plattform-Module hinweg im agilen Scrum-Team – von der Kursverwaltung bis zur Zertifikats-Engine, in Frontend und Backend.",
        "Entwicklung skalierbarer Backend-Services (**NestJS**, **GraphQL**) mit klar abgegrenzten Domänen in einer Microservice-Architektur.",
        "Umsetzung responsiver **Angular**-Oberflächen (Angular Material, **NgRx**) mit Fokus auf Wiederverwendbarkeit und Wartbarkeit.",
        "Bereitstellung über **Azure** (Azure DevOps Pipelines, **Docker**) mit automatisierten Builds und Deployments.",
      ],
      results: [
        "Skalierbare Microservice-Plattform im produktiven Einsatz bei namhaften Konzernen (**Daimler**, **VW**, **ThyssenKrupp** u. a.).",
        "Hoher Individualisierungsgrad für passgenaue, unternehmensspezifische Schulungen: jeder Konzern bespielt dieselbe Plattform mit eigenen Schulungen.",
        "Automatisierte Zertifikatsvergabe und Fortschrittsanalyse zur Steigerung der Abschlussquoten.",
        "Enge, funktionsübergreifende Zusammenarbeit mit Produkt und Design über zweieinhalb Jahre – vom ersten Ausbau bis zum produktiven Betrieb bei mehreren Großkunden.",
      ],
      tech: ["TypeScript", "Angular", "Node.js", "NestJS", "Express.js", "REST API", "GraphQL", "MongoDB", "Mongoose", "NgRx", "RxJS", "Angular Material", "SCSS", "Figma", "Microsoft Azure", "Azure DevOps", "Azure Pipelines", "Azure App Service", "Azure Blob Storage", "Docker", "CI/CD", "JWT", "OAuth 2.0", "Single Sign-On (SSO)", "Learning Management System (LMS)", "Video-Streaming", "Microservices", "Clean Architecture"],
    },
    {
      num: "09",
      cat: "HealthTech / Medizintechnik",
      period: "01/2019 – 05/2020 · 1 Jahr 5 Monate",
      dates: "01/2019 – 05/2020",
      duration: "~1 Jahr 5 Monate",
      name: "Medizingeräte-Managementsystem",
      role: "Full-Stack Engineer",
      client: "Krankenhauskette (anonymisiert)",
      overviewRole: "Full-Stack",
      cover: "medizingeraete-ms.jpg",
      meta: [
        { label: "Team:", value: "2–4 Personen" },
        { label: "Standort:", value: "Deutschland · Vor Ort / Hybrid" },
        { label: "Projektsprache:", value: "Deutsch" },
        { label: "Sichtbarkeit:", value: "HealthTech-Projekt für eine Krankenhauskette (anonymisiert)" },
        { label: "Methodik:", value: "Scrumban" },
      ],
      responsibilities: [
        "Mitentwicklung aller Bereiche einer Software zur Verwaltung medizinischer Geräte über mehrere Krankenhäuser – als Werkzeug für Techniker zur Vereinfachung von Wartung und Reparatur.",
        "Umsetzung der Geräte- und **Stammdatenverwaltung** (Krankenhaus, Standort, Gerätespezifikationen) auf Basis einer sauber geschichteten Architektur (**Clean Architecture**, **Dependency Injection**).",
        "Entwicklung einer detaillierten Wartungshistorie (Zeitpunkt und Art der durchgeführten Arbeiten) sowie eines gerätebezogenen **Dokumentenmanagements**.",
        "Implementierung der Störungserfassung durch das Pflegepersonal zur schnellen Weitergabe an die Technik.",
        "Umsetzung einer mandantenfähigen Filterung nach Krankenhaus (**Multi-Tenancy**) sowie Anbindung der Microsoft-Anmeldung über **O365 Identity**.",
        "Entwicklung einer typsicheren REST-API (**ASP.NET Core Web API**, Swagger/**OpenAPI**) mit sauberer Schichtung und **Dependency Injection**.",
        "Datenmodellierung und -zugriff mit **Entity Framework Core** (Code-First-Migrations) auf **MSSQL**.",
        "Automatisierte Builds über Azure DevOps Pipelines.",
      ],
      results: [
        "Vollständige, mandantenfähige Geräteverwaltung mit Wartungshistorie und **Dokumentenmanagement** umgesetzt.",
        "Strukturierte technische Grundlage für effizientere Wartungs- und Reparaturprozesse der Technik.",
        "Über ein Jahr Mitwirkung in einem kleinen, eng abgestimmten Team an einer sicherheitskritischen Anwendung im Krankenhausumfeld – mit Fokus auf Sorgfalt, Nachvollziehbarkeit und stabile Auslieferung.",
      ],
      tech: ["C#", ".NET Core", "ASP.NET Core", "ASP.NET Core Web API", "OpenAPI", "Swagger", "TypeScript", "React", "Entity Framework Core", "Datenmodellierung", "Microsoft SQL Server (MSSQL)", "Fluent UI", "Redux", "React Router", "Axios", "Single Page Application (SPA)", "Dependency Injection", "JWT", "O365 Identity", "Role-Based Access Control (RBAC)", "Multi-Tenancy", "Stammdatenverwaltung", "Dokumentenmanagement", "Microsoft Azure", "Azure SQL", "Azure DevOps", "Docker", "CI/CD", "Clean Architecture"],
    },
  ],
};

const en = {
  lang: "en",
  asOf: asOf.en,
  contact,
  headerName: "Nikita Petrich · Freelance Senior Full-Stack & AI Engineer",
  headerPlace: "Munich, Germany",
  pageLabel: "Page",

  profile: {
    quote: "“Anything done manually twice gets automated”",
    name: "Nikita Petrich",
    role: "Freelance Senior Full-Stack & AI Engineer",
    photo: "profile.jpg",
    lines: [
      [
        { label: "Phone:", value: contact.phone, href: `tel:${contact.phone.replace(/\s/g, "")}` },
        { label: "Mail:", value: contact.mail, href: `mailto:${contact.mail}` },
        { label: "Web:", value: contact.web, href: `https://${contact.web}` },
      ],
      [
        {
          label: "Location:",
          value:
            "Remote (preferred) · Munich hybrid: 1–2 days/week · Long-distance travel: 1–2 days/month (if needed)",
        },
      ],
      [{ label: "Onboarding:", value: "on-site at the start (if needed)" }],
      [
        { label: "Availability:", value: "immediately available · full-time (full capacity)" },
        { label: "Rate:", value: "on request" },
      ],
      [
        {
          label: "Qualification:",
          value: "IHK-certified Application Developer (Fachinformatiker, Cologne)",
        },
      ],
      [{ label: "Experience:", value: "7+ years" }],
    ],
    tagGroups: [
      {
        title: "Focus areas",
        tags: [
          "LLM integration",
          "RAG",
          "GDPR-compliant AI architecture",
          "AI-powered automation",
          "Agentic coding / AI engineering",
          "TypeScript",
          "Python",
          "Backend (NestJS · Node.js · FastAPI)",
          "Frontend (Next.js · React · Angular)",
          "PostgreSQL",
          "Clean Architecture",
          "Microservices",
          "CI/CD",
          "Docker",
        ],
      },
      {
        title: "Languages",
        tags: ["German · Native", "English · B2 · US/EU remote-team experience"],
      },
      {
        title: "Way of working",
        tags: [
          "results-oriented",
          "self-driven & reliable",
          "autonomous, asynchronous way of working",
          "clear communication (EN/DE)",
        ],
      },
      {
        title: "Profiles",
        tags: [
          { text: "Website", href: "https://sequenz.io" },
          { text: "LinkedIn", href: "https://linkedin.com/in/nikita-petrich" },
          { text: "GitHub", href: "https://github.com/nikita-petrich" },
          { text: "freelancermap", href: "https://www.freelancermap.de/profil/nikita-petrich" },
          { text: "Malt", href: "https://www.malt.de/profile/nikitapetrich" },
          { text: "Certificates", href: "https://sequenz.io/en/certificates" },
        ],
      },
    ],
    intro: [
      "I'm a freelance Senior Full-Stack & AI Engineer focused on AI: **LLM integration, RAG and AI-driven automation** – from architecture all the way to stable production.",
      "My guiding principle: **anything done manually twice gets automated.** That applies to my clients' processes as much as to my own work. In logistics, a route management system I built saves **up to 1,000 hours a year** through automated document workflows; in retail, **up to 40 hours of admin work per month**; at a notary's office, client phone enquiries dropped by **up to 70 %**.",
      "I apply the same logic to development itself. I work consistently with **agentic coding and AI engineering workflows** (Claude Code, Cursor, Code Rabbit, MCP) – spec-driven, with AI-assisted test generation and agentic review processes. This isn't a gimmick, it's the reason for unusual speed at consistent quality: a complete cross-platform app from first commit to handover **in roughly two months**, as the sole developer.",
      "How I work: **independently, remote and asynchronously**. I don't need daily direction, just a clear goal – I'll figure out the path there myself and speak up before anything slips. I document decisions, ship tested and review-ready code, and flag early when a requirement turns out to be technically more expensive than expected. I communicate in German and English.",
      "Technically: **TypeScript and Python**, backends with NestJS, Node.js and FastAPI, frontends with Next.js, React and Angular, plus PostgreSQL, Docker, CI/CD and cloud on Azure or GCP. Clean Architecture and microservices are standard; **GDPR compliance and Secure by Design** are built in from day one.",
      "I've done this inside a **20-person engineering team** – most recently on an AI-powered LegalTech platform with **more than 3,000 customers** – and as a sole developer with full product ownership. Over **seven years** across LegalTech, HealthTech, e-commerce, EdTech and logistics.",
    ],
    cta: {
      question: "Does this fit what you have in mind?",
      text: "Book a ",
      link: "free intro call",
      href: "https://calendar.notion.so/meet/petrichnikita/initial-consultation-30-min",
    },
  },

  skills: {
    title: "Skills & Expertise",
    subtitleA: "Complete overview of my technical skills",
    subtitleB: "Continued — Methodology, Compliance, Tooling & Domains",
    categories: [
      {
        num: "01",
        name: "AI, LLM & AI Engineering",
        items: ["LLM Integration", "RAG (Retrieval Augmented Generation)", "Prompt Engineering", "Embeddings", "Vector Databases", "pgvector", "Semantic Search", "Document Analysis", "OCR", "LangChain", "OpenAI API", "Azure OpenAI", "Anthropic Claude API", "Hugging Face", "Ollama", "AI Agents", "Agentic Software Engineering", "AI-Powered Automation", "AI Engineering", "Artificial Intelligence", "GDPR-Compliant AI Architecture"],
      },
      {
        num: "02",
        name: "Agentic Coding",
        items: ["Claude Code", "Cursor AI", "GitHub Copilot", "Code Rabbit", "ChatGPT", "Lovable", "v0", "Claude Code Hooks", "Slash Commands", "Agent Skills", "Subagents", "Multi-Agent Workflows", "Model Context Protocol (MCP)", "Agentic Coding", "Context Engineering", "Spec-Driven Development", "Agentic Pull-Request Workflows", "AI-Powered Test Generation"],
      },
      {
        num: "03",
        name: "Programming Languages",
        items: ["TypeScript", "JavaScript", "Python", "C#", "SQL", "Bash", "HTML", "CSS", "SCSS", "XML", "UML"],
      },
      {
        num: "04",
        name: "Backend & Frameworks",
        items: ["Node.js", "NestJS", "Express.js", "Fastify", "FastAPI", "Flask", "ASP.NET Core", ".NET Core", "GraphQL", "REST API", "OpenAPI", "Swagger", "WebSockets", "Webhooks", "Message Queues", "BullMQ", "RabbitMQ", "Backend Development", "Object-Oriented Programming (OOP)"],
      },
      {
        num: "05",
        name: "Frontend",
        items: ["React", "Next.js", "Angular", "React Native", "Ionic", "Capacitor", "Cross-Platform Development", "iOS", "Android", "Redux", "NgRx", "RxJS", "TanStack Query", "React Hook Form", "React Router", "Axios", "Zod", "Tailwind CSS", "shadcn/ui", "Material UI (MUI)", "Fluent UI", "Single Page Application (SPA)", "Progressive Web App (PWA)", "Server-Side Rendering (SSR)", "Internationalization (i18n)", "Frontend Development", "Web Development"],
      },
      {
        num: "06",
        name: "Design & UX",
        items: ["Figma", "Wireframing", "Prototyping", "Design System", "Design Tokens", "Component Libraries", "Storybook", "UI/UX Design", "UI Implementation", "Responsive Design", "Mobile First", "Accessibility (WCAG)", "Usability", "User Flows", "Onboarding Flows", "Information Architecture", "UX Writing", "Microcopy", "Design Reviews"],
      },
      {
        num: "07",
        name: "Databases & Data",
        items: ["PostgreSQL", "MySQL", "MariaDB", "Microsoft SQL Server (MSSQL)", "MongoDB", "Mongoose", "NoSQL", "SQLite", "Redis", "Cloud Firestore", "Prisma", "MikroORM", "TypeORM", "Drizzle ORM", "Entity Framework Core", "Data Modeling", "Data Architecture", "DTOs", "Data Synchronization", "ETL", "CSV Processing", "Caching", "Idempotency"],
      },
      {
        num: "08",
        name: "DevOps, Cloud & Infrastructure",
        items: ["Docker", "Docker Compose", "CI/CD", "Continuous Integration", "GitHub Actions", "GitLab CI", "Azure Pipelines", "Jenkins", "Nginx", "Sentry", "Monitoring", "Observability", "Linux", "Ubuntu", "Self-Hosting", "Microsoft Azure", "Azure Functions", "Azure App Service", "Azure Blob Storage", "Azure SQL", "Google Cloud Platform (GCP)", "Amazon Web Services (AWS)", "Hetzner", "IONOS", "Digital Ocean", "Vercel", "Supabase", "Firebase", "Cloud Functions", "Cloud Storage", "Firebase Cloud Messaging (FCM)", "Firebase Hosting", "DevOps", "DevSecOps"],
      },
      {
        num: "09",
        name: "Auth & Security",
        items: ["JWT", "OAuth 2.0", "Single Sign-On (SSO)", "better-auth", "Firebase Authentication (Auth)", "Firebase Security Rules", "Authentication", "Role-Based Access Control (RBAC)", "Row Level Security", "SSL/TLS", "End-to-End Encryption", "O365 Identity", "Microsoft Entra ID (formerly Azure Active Directory)", "Secure by Design", "IT Security"],
      },
      {
        num: "10",
        name: "Architecture & Principles",
        items: ["Software Architecture", "Clean Architecture", "Clean Code", "SOLID", "Design Patterns", "Domain-Driven Design", "Separation of Concerns", "Dependency Injection", "Microservices", "Event-Driven Architecture", "Monorepo", "Nx", "Turborepo", "Scalable Architecture", "System Integration", "Platform Migration", "Middleware", "API-First", "Resilience Patterns", "Type Safety", "MVP Development"],
      },
      {
        num: "11",
        name: "Methodology & Collaboration",
        items: ["Agile Methods", "Scrum", "Kanban", "Scrumban", "Code Reviews", "Test-Driven Development (TDD)", "Software Development", "Project Management", "IT Consulting", "Requirements Engineering", "Remote Work", "Public Speaking"],
      },
      {
        num: "12",
        name: "Business & Strategy",
        items: ["IT Strategy", "Digital Strategy", "Digital Transformation", "Process Digitization", "Product Ownership", "Entrepreneurship"],
      },
      {
        num: "13",
        name: "Data Privacy & Compliance",
        items: ["GDPR", "Privacy by Design", "Data Minimization", "Data Processing Agreement (DPA)", "EU AI Act", "AI Governance", "GoBD", "Audit-Proof Record-Keeping", "EU Hosting", "Digital Sovereignty", "German Accessibility Act (BFSG)", "European Accessibility Act (EAA)"],
      },
      {
        num: "14",
        name: "Testing & QA",
        items: ["Jest", "Vitest", "Cypress", "Playwright", "React Testing Library", "Unit Testing", "Integration Testing", "End-to-End Testing", "Postman", "API Testing", "Test Automation"],
      },
      {
        num: "15",
        name: "Tooling",
        items: ["Git", "GitHub", "GitLab", "Husky", "Visual Studio Code", "Visual Studio", "Jira", "Linear", "Azure DevOps", "Bluedot", "HubSpot", "Cal.com", "Slack", "Google Workspace (Meet, APIs)", "Amplitude", "Product Analytics"],
      },
      {
        num: "16",
        name: "Domains & Industries",
        items: ["LegalTech", "GovTech", "Law Firm Software", "Notary Services", "Client Portal", "Document Management", "HealthTech", "Medical Technology", "Maintenance Management", "ERP", "Inventory Management", "Warehouse Management", "Invoicing", "Order Management", "CRM", "Accounting", "Master Data Management", "Multi-Tenancy", "Stripe", "SEPA", "Payment Processing", "Logistics", "Route Planning", "PDF Generation", "DOCX Generation", "Digital Archiving", "EdTech", "E-Learning", "Learning Management System (LMS)", "IoT", "Device Pairing", "Consumer Electronics", "Social Media", "SaaS", "Platform Development"],
      },
      {
        num: "17",
        name: "Roles & Profile",
        items: ["Senior Full-Stack Engineer", "AI Engineer", "Software Engineer", "Freelance Developer", "Interim CTO", "Technical Consultant", "Certified Application Developer (Fachinformatiker)", "German (Native)", "English B2", "Munich", "DACH"],
      },
    ],
  },

  overview: {
    title: "Project Overview",
    subtitle: "All projects at a glance — with direct links to each detail page",
  },

  labels: {
    role: "Role:",
    client: "Client:",
    team: "Team:",
    location: "Location:",
    language: "Project Language:",
    website: "Website:",
    method: "Methodology:",
    visibility: "Visibility:",
    responsibilities: "Responsibilities",
    results: "Results",
    technologies: "Technologies",
    recommendation: "Recommendation",
  },

  projects: [
    {
      num: "01",
      cat: "LegalTech / GovTech",
      period: "04/2025 – present · 15 months",
      dates: "04/2025 – present",
      duration: "~15 months",
      name: "BESCHEIDKLAR",
      subtitle: "AI-Powered LegalTech SaaS Platform",
      role: "Founder & CTO",
      client: "Own Product",
      clientHref: "https://bescheidklar.de",
      overviewRole: "Founder & CTO",
      cover: "bescheidklar.jpg",
      meta: [
        { label: "Team:", value: "Solo (sole developer) · own product (side project)" },
        { label: "Location:", value: "Lower Saxony, Germany · Remote" },
        { label: "Project Language:", value: "German" },
        { label: "Website:", value: "bescheidklar.de", href: "https://bescheidklar.de" },
        { label: "Methodology:", value: "Self-directed · direct product ownership" },
      ],
      responsibilities: [
        "Designed and built a two-sided LegalTech SaaS platform with a modular, service-oriented architecture — combining AI-powered document analysis (**Azure OpenAI**) with a regional licensing model for law firms.",
        "Designed and implemented a multi-stage **AI pre-screening pipeline** for official notices and terminations (in progress): extraction → deadline check → plausibility and success assessment, with structured case preparation.",
        "Automated, GDPR-compliant handoff of qualified leads (incl. uploaded/photographed documents, calculations, and AI results) directly into the system of matching specialists (lawyers, law clinics) — including contact details, producing an immediately actionable case lead.",
        "Built an AI-powered advice section with **RAG**-based content generation — articles and recommended actions for affected individuals (e.g. after termination or a rejection notice).",
        "Covered multiple legal domains (legal, social, and labor law) via an extensible, multilingual, low-barrier web interface.",
        "Full ownership of architecture, tech stack, EU-infrastructure hosting, and a secure-by-design compliance concept (**EU AI Act**, **GDPR**, **German Legal Services Act**).",
        "Built type-safe end-to-end data flows (**TypeScript**, **DTOs**, **Zod**) with automated **CI/CD** delivery (**GitHub Actions**, **Docker**), monitoring/error tracking (**Sentry**), and test coverage (**Vitest**, **Playwright**).",
      ],
      results: [
        "MVP delivered single-handedly — architecture, platform and operation on EU infrastructure from one source.",
        "Compliance built into the product design rather than retrofitted: the EU AI Act, the GDPR and the limits of the German Legal Services Act were part of the plan from the start.",
        "Addressable market: **167,547** admitted lawyers in Germany (German Federal Bar, 1 Jan 2026); scalable model with minimal fixed costs.",
        "Target: up to **10,000** automated pre-screenings per month via AI-powered initial assessment.",
        "Target: up to **80 %** less manual case intake through AI intake and automated lawyer routing.",
        "Target: predictable inflow of pre-qualified cases for partner law firms instead of costly manual initial assessment.",
      ],
      tech: ["TypeScript", "Python", "Next.js", "React", "FastAPI", "LLM Integration", "OpenAI API", "Azure OpenAI", "RAG (Retrieval Augmented Generation)", "Prompt Engineering", "Embeddings", "pgvector", "OCR", "Document Analysis", "LangChain", "PostgreSQL", "Redis", "Tailwind CSS", "shadcn/ui", "Stripe", "JWT", "OAuth 2.0", "Docker", "GitHub Actions", "CI/CD", "Hetzner", "Linux", "Ubuntu", "Slack", "Husky", "Microservices", "Clean Architecture", "SaaS", "EU AI Act", "GDPR", "Privacy by Design", "Product Ownership"],
    },
    {
      num: "02",
      cat: "LegalTech / Immigration",
      period: "12/2025 – 04/2026 · 5 months",
      dates: "12/2025 – 04/2026",
      duration: "~5 months",
      name: "Manifest OS",
      subtitle: "AI-Powered Immigration Platform",
      role: "Full-Stack Engineer (AI Feature Integration)",
      client: "Manifest Law",
      clientHref: "https://manifestlaw.com",
      overviewRole: "Full-Stack (AI features)",
      recommendation: true,
      cover: "manifest-os.jpg",
      meta: [
        {
          label: "Team:",
          value:
            "~20 engineers across 4 teams (platform, AI, full-stack) · cross-functional collaboration with product, design, and tech leads",
        },
        { label: "Location:", value: "New York, USA · Remote" },
        { label: "Project Language:", value: "English" },
        { label: "Website:", value: "manifestlaw.com", href: "https://manifestlaw.com" },
        { label: "Methodology:", value: "Scrum · autonomous way of working" },
      ],
      responsibilities: [
        "Independently implemented production AI features: event-driven enrichment of attorney intake-call leads — meeting recordings are transcribed via **Bluedot** and processed resiliently (retry, idempotency) through a webhook, a **BullMQ** queue, and the **OpenAI** integration; structured results flow back automatically into the core systems.",
        "AI-powered evidence processing: uploaded case documents (e.g. ID scans, birth certificates, proofs) are automatically analyzed, classified, and consistently named.",
        "Contributed to consolidating four separate portals (B2B, B2C, Lawyer, Ops) and one API into a unified “B2X” portal — in a team of four engineers, owning the full-stack migration of the B2B and Ops areas, including merging the data model and UI.",
        "Introduced app-wide event tracking (**Amplitude**) to analyze user behavior — identifying weak points and friction as a data foundation for product and data analytics.",
        "Built resilient, event-driven backend services (**NestJS**, **BullMQ**) with retry, idempotency, and error-handling strategies for reliable background processing.",
        "Delivered within a monorepo with clearly scoped feature modules to enable a fast future split into microservices, with type-safe interfaces (**TypeScript**, **DTOs**) and automated tests (**Jest**, **Playwright**) in the CI/CD pipeline.",
        "Worked closely in code reviews and used AI-powered tools (**Claude Code**, **Cursor AI**, **Code Rabbit**) to safeguard quality and development speed.",
      ],
      results: [
        "Part of a roughly 20-person engineering team on an established platform (company valuation in the range of **~$60M USD**).",
        "AI features running in production: intake-call leads and case documents are enriched, classified and named without manual rework.",
        "Application-wide event tracking established as a shared data foundation for product and data analytics.",
        "Refactoring initiatives in the migrated B2B and Ops areas: existing structures simplified and geared towards better maintainability.",
        "Platform with **over 3,000 customers**, **150+** corporate programs and more than 100 lawyers (team result).",
        "Up to **15 %** higher approval rates versus the USCIS average (team result).",
      ],
      tech: ["TypeScript", "Python", "Next.js", "React", "NestJS", "Node.js", "Fastify", "Express.js", "REST API", "Webhooks", "DTOs", "BullMQ", "RabbitMQ", "LLM Integration", "OpenAI API", "Anthropic Claude API", "Model Context Protocol (MCP)", "Bluedot", "HubSpot", "Cal.com", "Amplitude", "PostgreSQL", "Redis", "MikroORM", "TanStack Query", "better-auth", "JWT", "Docker", "Linux", "Ubuntu", "Google Cloud Platform (GCP)", "GitHub Actions", "CI/CD", "Claude Code", "Cursor AI", "Code Rabbit", "Linear", "Figma", "Slack", "Playwright", "Husky", "Microservices", "Event-Driven Architecture", "Idempotency", "Clean Architecture"],
    },
    {
      num: "03",
      cat: "Social Media / Mobile App",
      period: "11/2025 – 12/2025 · 2 months",
      dates: "11/2025 – 12/2025",
      duration: "~2 months",
      name: "RateUp",
      subtitle: "Rating App for Web, iOS and Android",
      role: "Sole Developer · Full-Stack",
      client: "Krutzfeld Tech GmbH",
      clientHref: "https://krutzfeld.tech",
      overviewRole: "Sole Developer · Full-Stack",
      cover: "rate-up.jpg",
      meta: [
        { label: "Team:", value: "Solo (sole developer) · client project" },
        { label: "Location:", value: "Zurich, Switzerland · Remote" },
        { label: "Project Language:", value: "German" },
        { label: "Website:", value: "krutzfeld.tech", href: "https://krutzfeld.tech" },
        { label: "Methodology:", value: "Self-directed" },
      ],
      responsibilities: [
        "Designed and built a social-media rating app (feed, ratings, profiles) from a single **Ionic/Angular** codebase — as an installable **PWA** on the web and as native builds for **iOS** and **Android** (**Capacitor**).",
        "Registration, login, and onboarding incl. profile creation via **Firebase Authentication**, secured with **Firebase Security Rules**.",
        "Built the social feed with filters, user posts, and media upload (**Cloud Firestore**, **Cloud Storage**).",
        "Server-side logic in **Cloud Functions**, with delivery via **Firebase Hosting** and a **CI/CD** pipeline (**GitHub Actions**) for all three platforms.",
        "Built a maintainable, handover-ready codebase: clearly layered structure, reusable components, type-safe models, unit tests, and consistent clean-code style (**SOLID**).",
      ],
      results: [
        "Delivered a finished product to the client — running as a PWA on the web and as a native app on iOS and Android from a single shared codebase.",
        "Fully built on **Firebase**: authentication, data storage, media storage, server logic, and delivery.",
        "Handover-ready codebase: consistent structure, reusable components, unit tests, and full type safety — the client team can continue without an onboarding hurdle.",
        "From first line of code to handover **in around two months**.",
      ],
      tech: ["TypeScript", "Angular", "Ionic", "Capacitor", "RxJS", "Cross-Platform Development", "iOS", "Android", "Progressive Web App (PWA)", "Responsive Design", "UI Implementation", "User Flows", "Firebase", "Firebase Authentication (Auth)", "Firebase Security Rules", "Cloud Firestore", "Cloud Storage", "Cloud Functions", "Firebase Cloud Messaging (FCM)", "Firebase Hosting", "Authentication", "Onboarding Flows", "Social Media", "Type Safety", "Unit Testing", "Clean Code", "SOLID", "Separation of Concerns", "Clean Architecture", "Git", "GitHub", "GitHub Actions", "CI/CD", "Linux", "Trello"],
    },
    {
      num: "04",
      cat: "IoT / Consumer Electronics",
      period: "08/2025 – 09/2025 · 2 months",
      dates: "08/2025 – 09/2025",
      duration: "~2 months",
      name: "AITOI",
      subtitle: "Interactive IoT Toy (MVP)",
      role: "Frontend Engineer",
      client: "AITOI",
      overviewRole: "Frontend Engineer",
      recommendation: true,
      cover: "aitoi.jpg",
      meta: [
        { label: "Team:", value: "Small cross-disciplinary team incl. hardware development" },
        { label: "Location:", value: "Frankfurt, Germany · Remote" },
        { label: "Project Language:", value: "German & English" },
        { label: "Visibility:", value: "internal system (code not public)" },
        { label: "Methodology:", value: "Self-directed · English-language coordination with hardware team" },
      ],
      responsibilities: [
        "Designed and built the IoT Wi-Fi onboarding for a connected AI toy via QR-code scan — incl. a guided setup flow, device pairing, and robust error handling.",
        "Implemented first-time device setup as well as later reconfiguration of settings via a platform-independent **Progressive Web App** (PWA).",
        "PWA dashboard for parents: follow, filter and review their children's play sessions.",
        "Integrated **Supabase** for authentication, data storage, and real-time sync between device and app (incl. **row level security**).",
        "Built a performant, platform-independent PWA architecture (**Next.js**) with a responsive UI.",
        "Defined and implemented type-safe data models and API interfaces (**TypeScript**, **DTOs**, **Zod**).",
        "Coordinated closely, in English, with the hardware team to define device-app communication and the setup protocols.",
        "Advised and guided the client from initial idea to an actionable **MVP** concept.",
      ],
      results: [
        "Fully functional **MVP** frontend in **~2–3 weeks of actual working time** — taken independently from concept through client coordination to the demo.",
        "Setup app and parent dashboard as one platform-independent PWA with real-time sync between the IoT device and the app.",
        "Scalable, documented architecture as a solid technical foundation for the product launch.",
        "Trusted, cross-functional collaboration with the hardware team throughout the project — despite the tight timeline, no friction at the device-app interface.",
      ],
      tech: ["TypeScript", "Next.js", "React", "Progressive Web App (PWA)", "Responsive Design", "Design System", "React Hook Form", "DTOs", "Device Pairing", "Supabase", "Supabase Realtime", "Row Level Security", "PostgreSQL", "Tailwind CSS", "shadcn/ui", "JWT", "Authentication", "Docker", "Linux", "Ubuntu", "CI/CD", "GitHub Actions", "Vitest", "Cursor AI", "Model Context Protocol (MCP)", "MVP Development", "Clean Architecture"],
    },
    {
      num: "05",
      cat: "LegalTech / Notary",
      period: "01/2025 – 05/2025 · 5 months",
      dates: "01/2025 – 05/2025",
      duration: "~5 months",
      name: "DiNo",
      subtitle: "Digital Notary",
      role: "Frontend Engineer",
      client: "LeXtorByte UG",
      clientHref: "https://digitales-notariat.de",
      overviewRole: "Frontend",
      recommendation: true,
      cover: "dino.jpg",
      meta: [
        { label: "Team:", value: "2–4 people" },
        { label: "Location:", value: "Oranienburg, Germany · Remote" },
        { label: "Project Language:", value: "German" },
        { label: "Website:", value: "digitales-notariat.de", href: "https://digitales-notariat.de" },
        { label: "Methodology:", value: "Scrumban" },
      ],
      responsibilities: [
        "Implemented frontend features to digitize notary processes with a focus on clear, traceable user flows — incl. client portal and notary portal.",
        "Built digital case management: structured data capture, digital case files, and seamless internal filing to speed up case processing.",
        "Contributed to extending a client portal for status tracking, secure document delivery, and privacy-compliant communication.",
        "Built reusable components and unified form validation (**React Hook Form**) to speed up feature development across the team.",
        "Initiative within the codebase: refactored existing code and fixed long-standing bugs — aimed at solutions that hold up over time.",
        "Coordinated closely with design and backend in a **Scrumban** rhythm to quickly translate new requirements into usable interfaces.",
      ],
      results: [
        "Per the provider, up to **70 %** fewer client phone inquiries.",
        "Per the provider, invoices are paid up to **30 days** sooner.",
        "Noticeably reduced administrative overhead and greater transparency through consistently digital, traceable processes.",
        "Consistent, modern UI across the client and notary portals, strengthening both client trust and notary-office efficiency.",
      ],
      tech: ["TypeScript", "React", "Python", "Flask", "REST API", "OpenAPI", "DTOs", "MariaDB", "MySQL", "Redux", "React Router", "React Hook Form", "Material UI (MUI)", "Single Page Application (SPA)", "User Flows", "Client Portal", "Digital Archiving", "JWT", "OAuth 2.0", "Role-Based Access Control (RBAC)", "GDPR", "Docker", "Nginx", "Linux", "Ubuntu", "GitLab", "Slack", "Clean Architecture"],
    },
    {
      num: "06",
      cat: "Retail & Automotive (Inventory Mgmt.)",
      period: "01/2024 – 12/2024 · 12 months · ongoing maintenance (side project)",
      dates: "01/2024 – 12/2024",
      duration: "~12 months",
      name: "AccountingOS",
      subtitle: "GoBD-Compliant Accounting & Inventory System",
      role: "Sole Developer · Full-Stack & AI",
      client: "HD Autoservice",
      overviewRole: "Sole Developer",
      recommendation: true,
      cover: "accounting-os.jpg",
      meta: [
        { label: "Team:", value: "Solo (sole developer) · client project" },
        { label: "Location:", value: "Salzgitter, Germany · Remote" },
        { label: "Project Language:", value: "German" },
        { label: "Visibility:", value: "internal system (code not public)" },
        { label: "Methodology:", value: "Self-directed" },
      ],
      responsibilities: [
        "Designed and built a feature-rich, **GoBD**-compliant accounting and inventory management system on top of a cleanly layered architecture (**Clean Architecture**).",
        "Designed and implemented a resilient data-sync service (“pipe service”) that processes supplier catalogs (auto parts) with up to **20M** CSV rows over a TLS-encrypted connection — with queuing, caching, retry logic, validation, deduplication, and data cleansing.",
        "Built the accounting module: invoices, credit notes, internal orders, PDF export, customer management, **inventory management**, order import with automatic order conversion, and **GoBD** record-locking.",
        "Coupled **inventory management** with invoice management: automatic stock deduction on invoice line items and notification when falling below minimum stock.",
        "Recursive resolution of foreign-key dependencies in input dialogs for consistent master-data maintenance.",
        "Customer and **master-data management** with role-based access control (admin, staff, tax advisor) and authentication via **better-auth**.",
        "Advised the client on technical approaches, architecture, and process optimization.",
        "Built type-safe **GraphQL** and REST interfaces (**NestJS**) with validation, error handling, and consistent data modeling (**MikroORM**, **DTOs**).",
        "Ongoing support (side project): maintenance, security updates, and further development.",
      ],
      results: [
        "According to the client, saves up to **40 hours** of admin work per month (up to **480 hours/year**) — about **€ 19,200** a year at an assumed labour cost of € 40 per hour.",
        "Cuts time spent on routine processes like invoicing and **inventory management** by up to **50 %**.",
        "Consistently digital, **GoBD**-compliant workflows with direct coupling of inventory and **accounting**.",
      ],
      tech: ["TypeScript", "Node.js", "NestJS", "Next.js", "React", "Fastify", "REST API", "GraphQL", "DTOs", "Type Safety", "Data Synchronization", "CSV Processing", "Message Queues", "Caching", "MariaDB", "PostgreSQL", "Redis", "MikroORM", "TanStack Query", "Tailwind CSS", "Inventory Management", "Warehouse Management", "Accounting", "ERP", "GoBD", "better-auth", "JWT", "Role-Based Access Control (RBAC)", "Docker", "Self-Hosting", "Linux", "Ubuntu", "CI/CD", "GitHub", "GitHub Actions", "Husky", "Claude Code", "Cursor AI", "Model Context Protocol (MCP)", "Microservices", "Clean Architecture"],
    },
    {
      num: "07",
      cat: "Logistics & Transport",
      period: "02/2021 – 05/2023 · 2 years 4 months · ongoing maintenance (side project)",
      dates: "02/2021 – 05/2023",
      duration: "~2 years 4 months",
      name: "Ladetrans",
      subtitle: "Truck Route Management for a Humanitarian Aid Organisation",
      role: "Sole Developer · Full-Stack & AI",
      client: "CDH Stephanus",
      clientHref: "https://cdh-stephanus.org",
      overviewRole: "Sole Developer",
      cover: "lkw-tourverwaltung.jpg",
      meta: [
        { label: "Team:", value: "Solo (sole developer) · client project" },
        { label: "Location:", value: "Bremen, Germany · Remote" },
        { label: "Project Language:", value: "German" },
        { label: "Website:", value: "cdh-stephanus.org", href: "https://cdh-stephanus.org" },
        { label: "Methodology:", value: "Self-directed" },
      ],
      responsibilities: [
        "Loading lists per trip: goods to be shipped, recipient addresses and drivers assembled in a single case.",
        "Every trip as one continuous case — create, edit, close and archive.",
        "Automated generation of the route documents from the captured data, among other things for border checks.",
        "Audit-proof archiving of completed trips including the proofs uploaded at the end of each trip.",
        "Sole responsibility for the backend architecture (**NestJS**, **Clean Architecture**), role-based access control (**better-auth**) and the self-hosted deployment (**Docker**, **Nginx**) including ongoing maintenance (side project).",
      ],
      results: [
        "According to the client, automated document processes save up to **1,000 hours** per employee per year — about **€ 40,000** annually at an assumed labour cost of € 40 per hour.",
        "According to the client, up to **30 %** higher logistics efficiency thanks to end-to-end management of the shipping trips.",
        "Markedly fewer transcription errors; every trip is archived audit-proof together with its documents and proofs.",
      ],
      tech: ["TypeScript", "Node.js", "NestJS", "Next.js", "React", "Fastify", "REST API", "GraphQL", "PostgreSQL", "Redis", "MikroORM", "React Router", "Tailwind CSS", "Single Page Application (SPA)", "Logistics", "Route Planning", "PDF Generation", "DOCX Generation", "Digital Archiving", "better-auth", "JWT", "Authentication", "Role-Based Access Control (RBAC)", "Docker", "Self-Hosting", "Linux", "Ubuntu", "CI/CD", "GitHub Actions", "Husky", "Claude Code", "Cursor AI", "Model Context Protocol (MCP)", "Slack", "Nginx", "Microservices", "Clean Architecture"],
    },
    {
      num: "08",
      cat: "EdTech / E-Learning",
      period: "05/2020 – 02/2023 · 2 years 10 months",
      dates: "05/2020 – 02/2023",
      duration: "~2 years 10 months",
      name: "XU Navigator",
      subtitle: "Enterprise Learning Platform",
      role: "Full-Stack Engineer",
      client: "XU Group",
      clientHref: "https://xu.de",
      overviewRole: "Full-Stack",
      recommendation: true,
      cover: "xu-navigator.jpg",
      meta: [
        { label: "Team:", value: "5–10 people" },
        { label: "Location:", value: "Bremen, Germany · Remote" },
        { label: "Project Language:", value: "German & English" },
        { label: "Website:", value: "xu.de", href: "https://xu.de" },
        { label: "Methodology:", value: "Scrum" },
      ],
      responsibilities: [
        "Co-developed “XU Navigator”, a scalable microservice learning platform for enterprise employees — for clients including **Daimler**, **VW**, and **ThyssenKrupp**.",
        "Built dynamically, tenant-specific course content (videos, podcasts, multiple-choice quizzes, articles) across clearly scoped services.",
        "Implemented learning-progress tracking incl. automatic certificate generation as well as an expert and community forum.",
        "Full-stack development across all platform modules within an agile Scrum team — from course management to the certificate engine, in both frontend and backend.",
        "Built scalable backend services (**NestJS**, **GraphQL**) with clearly scoped domains in a microservice architecture.",
        "Built responsive **Angular** interfaces (Angular Material, **NgRx**) focused on reusability and maintainability.",
        "Deployed via **Azure** (Azure DevOps Pipelines, **Docker**) with automated builds and deployments.",
      ],
      results: [
        "Scalable microservice platform in production use at major enterprises (**Daimler**, **VW**, **ThyssenKrupp**, and others).",
        "High degree of customization for tailored, company-specific training programs: every corporation runs its own training on the same platform.",
        "Automated certificate issuance and progress analytics to boost completion rates.",
        "Close, cross-functional collaboration with product and design over two and a half years — from initial rollout to production use at multiple enterprise clients.",
      ],
      tech: ["TypeScript", "Angular", "Node.js", "NestJS", "Express.js", "REST API", "GraphQL", "MongoDB", "Mongoose", "NgRx", "RxJS", "Angular Material", "SCSS", "Figma", "Microsoft Azure", "Azure DevOps", "Azure Pipelines", "Azure App Service", "Azure Blob Storage", "Docker", "CI/CD", "JWT", "OAuth 2.0", "Single Sign-On (SSO)", "Learning Management System (LMS)", "Video Streaming", "Microservices", "Clean Architecture"],
    },
    {
      num: "09",
      cat: "HealthTech / Medical Devices",
      period: "01/2019 – 05/2020 · 1 year 5 months",
      dates: "01/2019 – 05/2020",
      duration: "~1 year 5 months",
      name: "Medical Device Management System",
      role: "Full-Stack Engineer",
      client: "Hospital Group (anonymized)",
      overviewRole: "Full-Stack",
      cover: "medizingeraete-ms.jpg",
      meta: [
        { label: "Team:", value: "2–4 people" },
        { label: "Location:", value: "Germany · On-site / Hybrid" },
        { label: "Project Language:", value: "German" },
        { label: "Visibility:", value: "HealthTech project for a hospital group (anonymized)" },
        { label: "Methodology:", value: "Scrumban" },
      ],
      responsibilities: [
        "Co-developed all areas of software to manage medical devices across multiple hospitals — a tool for technicians to simplify maintenance and repair.",
        "Built device and **master-data management** (hospital, location, device specifications) on top of a cleanly layered architecture (**Clean Architecture**, **Dependency Injection**).",
        "Developed a detailed maintenance history (timing and type of work performed) plus device-linked **document management**.",
        "Implemented fault reporting by nursing staff for fast handoff to technicians.",
        "Built multi-tenant filtering by hospital (**Multi-Tenancy**) plus integration of Microsoft sign-in via **O365 Identity**.",
        "Built a type-safe REST API (**ASP.NET Core Web API**, Swagger/**OpenAPI**) with clean layering and **dependency injection**.",
        "Data modeling and access with **Entity Framework Core** (code-first migrations) on **MSSQL**.",
        "Automated builds via Azure DevOps Pipelines.",
      ],
      results: [
        "Delivered complete, multi-tenant device management with maintenance history and **document management**.",
        "Structured technical foundation for more efficient maintenance and repair processes.",
        "Contributed for over a year as part of a small, closely aligned team on a safety-critical application in a hospital setting — with a focus on rigor, traceability, and stable delivery.",
      ],
      tech: ["C#", ".NET Core", "ASP.NET Core", "ASP.NET Core Web API", "OpenAPI", "Swagger", "TypeScript", "React", "Entity Framework Core", "Data Modeling", "Microsoft SQL Server (MSSQL)", "Fluent UI", "Redux", "React Router", "Axios", "Single Page Application (SPA)", "Dependency Injection", "JWT", "O365 Identity", "Role-Based Access Control (RBAC)", "Multi-Tenancy", "Master Data Management", "Document Management", "Microsoft Azure", "Azure SQL", "Azure DevOps", "Docker", "CI/CD", "Clean Architecture"],
    },
  ],
};

export const cv = { de, en };
