"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowUpRight,
  Award,
  Calendar,
  ChevronRight,
  ExternalLink,
  FileText,
  ShieldCheck,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { certificates, type Certificate } from "@/lib/data";
import { useSearchTracking } from "@/lib/analytics/use-search-tracking";

import { DatabaseToolbar, type GalleryView } from "./database-toolbar";
import { AccentTag, SkillTag } from "./blocks";
import { bannerBg } from "./cover-banner";
import { EmptyState, GalleryGrid, TableShell, useGallery } from "./gallery";
import { ModalShell } from "./modal-shell";

/* Permanent, shareable link to the certificate document itself: the
   self-hosted PDF at /zertifikate/<slug>.pdf, or an official external URL when
   not yet hosted. Always opened in a new tab. */
export const certHref = (c: Certificate) =>
  c.externalUrl ?? `/zertifikate/${c.slug}.pdf`;

/* Detail page with the full scope of the certificate. Opens as a dialog via
   the intercepting route and renders standalone on a hard load. */
export const certPageHref = (c: Certificate) => `/zertifikate/${c.slug}`;

const documentLabel = (c: Certificate) =>
  c.externalUrl ? `Auf ${c.issuer} ansehen` : "PDF öffnen";

/* Per-platform pill styling (Notion select colours). */
const issuerPill: Record<Certificate["issuer"], string> = {
  Scrimba: "bg-[var(--pill-green)] text-[#2a6b3a]",
  "Code with Mosh": "bg-[var(--pill-blue)] text-[#24618a]",
  Udemy: "bg-[var(--pill-purple)] text-[#6b4a86]",
};

function IssuerPill({ issuer }: { issuer: Certificate["issuer"] }) {
  return (
    <span
      className={cn(
        "shrink-0 rounded-[4px] px-[7px] py-[2px] text-[11px] font-semibold",
        issuerPill[issuer],
      )}
    >
      {issuer}
    </span>
  );
}

const previewAlt = (c: Certificate) =>
  `Zertifikat „${c.title}“ von ${c.issuer}, ausgestellt ${c.date}`;

/* Certificate "cover": the pre-rendered first page of the PDF (generated by
   scripts/certificate-previews.mjs), shown in full on the warm banner
   background — portrait and landscape certificates both stay readable because
   the page is contained, never cropped. The frame is a little taller than the
   16/9 of the project covers so the portrait pages get room; certificates
   without a self-hosted PDF fall back to a flatter branded band. */
function CertificateCover({
  cert,
  variant,
}: {
  cert: Certificate;
  variant: "card" | "modal";
}) {
  const card = variant === "card";
  // One frame for every card so the covers line up across a gallery row; the
  // dialog gets a wide banner, flatter when there is no page to show.
  const frame = card
    ? "aspect-[4/3]"
    : cert.preview
      ? "aspect-[16/9] sm:aspect-[16/8]"
      : "aspect-[16/6]";

  return (
    <div
      className={cn("relative w-full overflow-hidden", frame)}
      style={{ backgroundImage: bannerBg }}
    >
      <div className="absolute inset-y-0 left-0 z-[1] w-[5px] bg-[var(--accent-o)]" />

      {cert.preview ? (
        <div
          className={cn(
            "absolute inset-0",
            card ? "p-2 pl-[13px]" : "p-4 pl-6 sm:p-5 sm:pl-8",
          )}
        >
          <Image
            src={cert.preview}
            alt={previewAlt(cert)}
            fill
            sizes={card ? "(max-width: 640px) 100vw, 340px" : "(max-width: 720px) 100vw, 680px"}
            className="object-contain drop-shadow-[0_2px_10px_rgba(15,15,15,0.18)]"
          />
        </div>
      ) : (
        <div className="flex h-full flex-col items-center justify-center gap-1.5 px-3 text-center">
          <Award size={30} strokeWidth={1.6} className="text-[var(--accent-o)]" />
          <span className="text-[10px] font-semibold tracking-[0.14em] text-[#6b614e] uppercase">
            {cert.issuer}
          </span>
        </div>
      )}
    </div>
  );
}

/* The scope fields join the search surface: a query like "Firebase", "MCP" or
   "Olof Paulson" should find the certificate that covers it. */
const certificateSearchText = (c: Certificate) =>
  [
    c.title,
    c.issuer,
    c.cat,
    c.tags.join(" "),
    c.summary,
    c.facts?.map((f) => f.value).join(" ") ?? "",
    c.outcomes?.join(" ") ?? "",
    c.curriculum
      ?.map((s) => `${s.title} ${s.lessons?.join(" ") ?? ""}`)
      .join(" ") ?? "",
  ].join(" ");
const certificateSortKey = (c: Certificate) => c.sort;

/* Table view: same target (the detail dialog) and analytics as the gallery
   cards, laid out as a CSS grid so cells stay simple <Link> children. */
const CERTIFICATE_COLS =
  "grid-cols-[minmax(200px,1.8fr)_minmax(120px,0.9fr)_minmax(100px,0.7fr)_minmax(140px,1.1fr)_28px]";

function CertificateTable({ certificates: rows }: { certificates: Certificate[] }) {
  return (
    <TableShell>
      <div className="min-w-[720px]">
        <div
          className={cn(
            "grid gap-3 border-b border-[rgba(55,53,47,0.09)] px-3 py-2 text-[12px] font-medium text-notion-gray",
            CERTIFICATE_COLS,
          )}
        >
          <div>Titel</div>
          <div>Aussteller</div>
          <div>Datum</div>
          <div>Kategorie</div>
          <div />
        </div>
        {rows.map((c) => (
          <Link
            key={c.slug}
            href={certPageHref(c)}
            scroll={false}
            data-analytics-event="certificate_open"
            data-analytics-prop-slug={c.slug}
            data-analytics-prop-issuer={c.issuer}
            data-analytics-prop-source="table"
            aria-label={`Zertifikat „${c.title}“ (${c.issuer}) — Details ansehen`}
            className={cn(
              "grid items-center gap-3 border-b border-[rgba(55,53,47,0.06)] px-3 py-2.5 text-[13px] transition-colors last:border-0 hover:bg-[rgba(55,53,47,0.02)]",
              CERTIFICATE_COLS,
            )}
          >
            <div className="truncate font-medium">{c.title}</div>
            <div className="min-w-0">
              <IssuerPill issuer={c.issuer} />
            </div>
            <div className="truncate text-notion-gray">{c.date}</div>
            <div className="min-w-0">
              <AccentTag label={c.cat} />
            </div>
            <ArrowUpRight size={14} strokeWidth={2} className="text-notion-gray" />
          </Link>
        ))}
      </div>
    </TableShell>
  );
}

/* Opens the certificate document in a new tab from inside a card or dialog
   link. Rendered as a span with a link role: a nested <a> inside the card's
   <Link> would be invalid HTML. */
function DocumentAction({
  cert,
  className,
  children,
  source,
}: {
  cert: Certificate;
  className?: string;
  children: React.ReactNode;
  source: string;
}) {
  const open = () =>
    window.open(certHref(cert), "_blank", "noopener,noreferrer");

  return (
    <span
      role="link"
      tabIndex={0}
      aria-label={`Zertifikat „${cert.title}“ als ${
        cert.externalUrl ? "Original" : "PDF"
      } in neuem Tab öffnen`}
      data-analytics-event="certificate_document_open"
      data-analytics-prop-slug={cert.slug}
      data-analytics-prop-issuer={cert.issuer}
      data-analytics-prop-target={cert.externalUrl ? "external" : "pdf"}
      data-analytics-prop-source={source}
      onClick={(e) => {
        e.preventDefault();
        e.stopPropagation();
        open();
      }}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          e.stopPropagation();
          open();
        }
      }}
      className={cn("relative z-[1] cursor-pointer", className)}
    >
      {children}
    </span>
  );
}

export function CertificateGallery() {
  const [view, setView] = useState<GalleryView>("gallery");
  const { query, setQuery, sortDirLabel, toggleSort, visible } = useGallery(
    certificates,
    certificateSearchText,
    certificateSortKey,
  );

  useSearchTracking("certificates", query, visible.length);

  return (
    <>
      <DatabaseToolbar
        view={view}
        onViewChange={setView}
        sortProp="Datum"
        sortPropIcon={<Calendar size={14} strokeWidth={1.9} />}
        sortDirLabel={sortDirLabel}
        onToggleSortDir={toggleSort}
        query={query}
        onQueryChange={setQuery}
      />

      {visible.length === 0 ? (
        <EmptyState />
      ) : view === "table" ? (
        <CertificateTable certificates={visible} />
      ) : (
        <GalleryGrid>
          {visible.map((c) => (
            <Link
              key={c.slug}
              href={certPageHref(c)}
              scroll={false}
              data-analytics-event="certificate_open"
              data-analytics-prop-slug={c.slug}
              data-analytics-prop-issuer={c.issuer}
              data-analytics-prop-source="gallery"
              aria-label={`Zertifikat „${c.title}“ (${c.issuer}) — Details ansehen`}
              style={{ boxShadow: "var(--notion-card-shadow)" }}
              className="group flex h-full cursor-pointer flex-col overflow-hidden rounded-lg bg-white text-left transition-colors hover:bg-[rgba(55,53,47,0.02)]"
            >
              <CertificateCover cert={c} variant="card" />
              <div className="flex flex-1 flex-col gap-[7px] p-[11px]">
                <div className="text-[15px] leading-[1.3] font-semibold">
                  {c.title}
                </div>
                <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-[12px] text-notion-gray">
                  <IssuerPill issuer={c.issuer} />
                  <span>
                    {c.date}
                    {c.detail ? ` · ${c.detail}` : ""}
                  </span>
                </div>
                <div className="mt-auto flex flex-wrap items-center gap-[6px] pt-0.5">
                  <AccentTag label={c.cat} />
                  {c.tags
                    .filter((t) => t !== c.cat)
                    .map((t) => (
                      <AccentTag key={t} label={t} />
                    ))}
                </div>
                <div className="flex flex-wrap items-center gap-x-3 gap-y-1 pt-1 text-[12px] font-medium text-[var(--accent-text)]">
                  <span className="flex items-center gap-1.5">
                    Umfang &amp; Inhalte
                    <ArrowUpRight
                      size={13}
                      strokeWidth={2}
                      className="opacity-70 transition-transform group-hover:translate-x-[1px] group-hover:-translate-y-[1px]"
                    />
                  </span>
                  <DocumentAction
                    cert={c}
                    source="gallery"
                    className="flex items-center gap-1.5 hover:underline"
                  >
                    {c.externalUrl ? (
                      <ExternalLink size={13} strokeWidth={2} />
                    ) : (
                      <FileText size={13} strokeWidth={2} />
                    )}
                    {documentLabel(c)}
                  </DocumentAction>
                </div>
              </div>
            </Link>
          ))}
        </GalleryGrid>
      )}
    </>
  );
}

/* Outbound button styles shared by the dialog's actions. */
const primaryAction =
  "inline-flex items-center gap-2 rounded-md bg-[var(--accent-o)] px-3.5 py-2 text-[13px] font-semibold text-white transition-opacity hover:opacity-90";
const secondaryAction =
  "inline-flex items-center gap-2 rounded-md border border-[rgba(55,53,47,0.16)] bg-white px-3.5 py-2 text-[13px] font-medium text-[#4a473f] transition-colors hover:bg-[rgba(55,53,47,0.04)]";

/* One syllabus chapter as a native <details> block: keyboard operable and
   searchable by the browser's find-in-page without any JavaScript. */
function CurriculumSection({
  section,
  open,
}: {
  section: NonNullable<Certificate["curriculum"]>[number];
  open: boolean;
}) {
  const { title, meta, lessons } = section;

  if (!lessons?.length) {
    return (
      <div className="border-b border-[rgba(55,53,47,0.08)] py-2.5 last:border-0">
        <div className="text-[14px] font-medium">{title}</div>
        {meta ? (
          <div className="mt-0.5 text-[12px] text-notion-gray">{meta}</div>
        ) : null}
      </div>
    );
  }

  return (
    <details
      open={open}
      className="group border-b border-[rgba(55,53,47,0.08)] last:border-0"
    >
      <summary className="flex cursor-pointer list-none items-start gap-2 py-2.5 marker:content-none hover:text-[var(--accent-text)] [&::-webkit-details-marker]:hidden">
        <ChevronRight
          size={15}
          strokeWidth={2.2}
          className="mt-[3px] shrink-0 text-notion-gray transition-transform group-open:rotate-90"
        />
        <span className="min-w-0 flex-1">
          <span className="text-[14px] font-medium">{title}</span>
          <span className="ml-2 text-[12px] text-notion-gray">
            {meta ?? `${lessons.length} Lektionen`}
          </span>
        </span>
      </summary>
      {/* Keyed by position: lesson titles repeat within a chapter (a course can
          have "Handling Errors" in both its backend and its frontend part). */}
      <ol className="mb-2.5 ml-[23px] flex list-decimal flex-col gap-[5px] pl-4 text-[13px] leading-[1.5] text-[#4a473f] marker:text-notion-gray">
        {lessons.map((lesson, i) => (
          <li key={`${i}-${lesson}`}>{lesson}</li>
        ))}
      </ol>
    </details>
  );
}

/* Shared by the intercepting modal route and the standalone page, which each
   pass their own onClose. Explains the scope of the certificate in full and
   links to the document itself in a new tab — via the preview at the top and
   via the primary action button. */
export function CertificateModal({
  certificate: c,
  onClose,
}: {
  certificate: Certificate;
  onClose: () => void;
}) {
  const docHref = certHref(c);
  const verifyUrl = c.verifyUrl ?? c.externalUrl;

  return (
    <ModalShell label={`Zertifikat: ${c.title}`} onClose={onClose}>
      <>
        {/* The preview is the most obvious place to click for the document
            itself, so it is a real link — a plain <a>, opened in a new tab. */}
        <a
          href={docHref}
          target="_blank"
          rel="noopener noreferrer"
          data-analytics-event="certificate_document_open"
          data-analytics-prop-slug={c.slug}
          data-analytics-prop-issuer={c.issuer}
          data-analytics-prop-target={c.externalUrl ? "external" : "pdf"}
          data-analytics-prop-source="modal_preview"
          aria-label={`Zertifikat „${c.title}“ als ${
            c.externalUrl ? "Original" : "PDF"
          } in neuem Tab öffnen`}
          className="group relative block"
        >
          <CertificateCover cert={c} variant="modal" />
          <span className="pointer-events-none absolute right-3 bottom-3 z-[1] inline-flex items-center gap-1.5 rounded-md bg-white/90 px-2.5 py-1.5 text-[12px] font-medium text-[#4a473f] opacity-0 shadow-sm backdrop-blur transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100">
            {c.externalUrl ? (
              <ExternalLink size={13} strokeWidth={2} />
            ) : (
              <FileText size={13} strokeWidth={2} />
            )}
            In neuem Tab öffnen
          </span>
        </a>

        <div className="px-6 py-7 sm:px-10 sm:py-9">
          <div className="text-[12px] font-semibold tracking-[0.06em] text-[var(--accent-text)] uppercase">
            {c.cat}
          </div>
          <h2 className="mt-2 text-[26px] leading-[1.2] font-bold tracking-[-0.01em]">
            {c.title}
          </h2>
          <div className="mt-2.5 flex flex-wrap items-center gap-x-2 gap-y-1.5 text-[13px] text-notion-gray">
            <IssuerPill issuer={c.issuer} />
            <span>
              {c.date}
              {c.detail ? ` · ${c.detail}` : ""}
            </span>
          </div>

          <div className="mt-5 flex flex-wrap items-center gap-2.5">
            <a
              href={docHref}
              target="_blank"
              rel="noopener noreferrer"
              data-analytics-event="certificate_document_open"
              data-analytics-prop-slug={c.slug}
              data-analytics-prop-issuer={c.issuer}
              data-analytics-prop-target={c.externalUrl ? "external" : "pdf"}
              data-analytics-prop-source="modal_button"
              className={primaryAction}
            >
              {c.externalUrl ? (
                <ExternalLink size={15} strokeWidth={2} />
              ) : (
                <FileText size={15} strokeWidth={2} />
              )}
              {c.externalUrl
                ? `Zertifikat auf ${c.issuer} ansehen`
                : "Zertifikat als PDF öffnen"}
            </a>
            {verifyUrl && !c.externalUrl ? (
              <a
                href={verifyUrl}
                target="_blank"
                rel="noopener noreferrer"
                data-analytics-event="certificate_verify_click"
                data-analytics-prop-slug={c.slug}
                data-analytics-prop-issuer={c.issuer}
                className={secondaryAction}
              >
                <ShieldCheck size={15} strokeWidth={2} />
                Auf {c.issuer} verifizieren
              </a>
            ) : null}
            {c.courseUrl ? (
              <a
                href={c.courseUrl}
                target="_blank"
                rel="noopener noreferrer"
                data-analytics-event="certificate_course_click"
                data-analytics-prop-slug={c.slug}
                data-analytics-prop-issuer={c.issuer}
                className={secondaryAction}
              >
                <ArrowUpRight size={15} strokeWidth={2} />
                Kursseite
              </a>
            ) : null}
          </div>

          <p className="mt-6 text-[15px] leading-[1.6] text-[#37352f]">
            {c.summary}
          </p>

          {c.facts?.length ? (
            <div className="mt-[22px] grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-[rgba(55,53,47,0.1)] bg-[rgba(55,53,47,0.09)] sm:grid-cols-3">
              {c.facts.map((f) => (
                <div key={f.label} className="bg-[#faf9f7] px-3.5 py-2.5">
                  <div className="text-[10px] font-semibold tracking-[0.06em] text-notion-gray uppercase">
                    {f.label}
                  </div>
                  <div className="mt-1 text-[13px] leading-[1.35] text-[#37352f]">
                    {f.value}
                  </div>
                </div>
              ))}
            </div>
          ) : null}

          {c.outcomes?.length ? (
            <>
              <h3 className="mt-6 mb-2.5 text-[12px] font-semibold tracking-[0.04em] text-notion-gray uppercase">
                Inhalte &amp; Kompetenzen
              </h3>
              <ul className="flex flex-col gap-[9px]">
                {c.outcomes.map((o) => (
                  <li key={o} className="flex gap-2.5 text-[14px] leading-[1.55]">
                    <span className="mt-[8px] h-[6px] w-[6px] shrink-0 rounded-full bg-[#37352f]" />
                    <span>{o}</span>
                  </li>
                ))}
              </ul>
            </>
          ) : null}

          {c.curriculum?.length ? (
            <>
              <h3 className="mt-6 mb-1 text-[12px] font-semibold tracking-[0.04em] text-notion-gray uppercase">
                Kursaufbau
              </h3>
              {c.curriculumNote ? (
                <p className="mb-1.5 text-[12px] leading-[1.5] text-notion-gray">
                  {c.curriculumNote}
                </p>
              ) : null}
              <div className="rounded-lg border border-[rgba(55,53,47,0.1)] bg-[#faf9f7] px-4 py-1">
                {c.curriculum.map((section, i) => (
                  <CurriculumSection
                    key={section.title}
                    section={section}
                    open={i === 0}
                  />
                ))}
              </div>
            </>
          ) : null}

          <h3 className="mt-6 mb-2.5 text-[12px] font-semibold tracking-[0.04em] text-notion-gray uppercase">
            Themen
          </h3>
          <div className="flex flex-wrap gap-[6px]">
            {c.tags.map((t) => (
              <SkillTag key={t} label={t} />
            ))}
          </div>
        </div>
      </>
    </ModalShell>
  );
}
